### ISSUE TITLE
Multiple group feature

### ISSUE THREAD

**Issue by zack77789** [bitnami/bitnami-docker-openldap#100]
### Name and Version

latest

### What is the problem this feature will solve?

It is not possible to initiate a container with multiple LDAP groups defined with multiple users within these groups. The current image only allows for a user to define many users in one LDAP group.

As I understand one has to initiate separate containers for different groups.

### What is the feature you are proposing to solve the problem?

Addition of env variable that allows for multiple LDAP group definitions not just single.

### What alternatives have you considered?

0

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
