### ISSUE TITLE
bitnami-docker-openldap: regression when adding LDAP_EXTRA_SCHEMAS

### ISSUE THREAD

**Issue by bourasom** [bitnami/bitnami-docker-openldap#102]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

bitnami/openldap:2.6
running 
```
docker run --name openldap -d -p 1389:1389 -p 1636:1636 -e LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis bitnami/openldap:2.6
```
The actual behavior is that they are not introduced

### What is the expected behavior?

The expected behavior is that the schemas are added to the instance's conf

### What do you see instead?

The actual behavior is that the schemas are not loaded

### Additional information

The issue is coming from the following supposed yes/true var
https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L59

When the `LDAP_EXTRA_SCHEMAS` is set the `LDAP_ADD_SCHEMAS` takes its value instead of yes causing the test in 
https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L469 is not passing

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
