### ISSUE TITLE
Add the rfc2307bis schema via option

### ISSUE THREAD

**Issue by StefanArts** [bitnami/bitnami-docker-openldap#105]
### Name and Version

bitnami/bitnami-docker-openldap:latest

### What is the problem this feature will solve?

Having an easy way to enable the standard schema rfc2307bis instead of the rfc2307(nis).
I wasn't able to enable it manually via the custom schema options

### What is the feature you are proposing to solve the problem?

Having an easy way to enable the standard schema rfc2307bis instead of the rfc2307(nis).
I wasn't able to enable it manually via the custom schema options

### What alternatives have you considered?

Using another docker solution than bitnami that already has this feature. I like bitnami though because it is regularly updated

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
