### ISSUE TITLE
Debian 11 container breaks custom ldif to encrypt stored passwords

### ISSUE THREAD

**Issue by bamhm182** [bitnami/bitnami-docker-openldap#109]
### Name and Version

bitnami/openldap:2.6.2-debian-11-r0

### What steps will reproduce the bug?

1. Create a container based on debian11 as seen above and the following custom LDIF
```
dn: olcDatabase={-1}frontend,cn=config
replace: olcPasswordHash
olcPasswordHash: {CRYPT}

dn: cn=config
replace: olcPasswordCryptSaltFormat
olcPasswordCryptSaltFormat: $6$rounds=150000%.16s
```
2. Drop into the container and set the password of a user:
```
ldappasswd -x -S "uid=bob,ou=users,${LDAP_ROOT}" -D "cn=${LDAP_ADMIN_USERNAME},${LDAP_ROOT}" -W -H ldap://127.0.0.1:1389
```
3. Run the following command to view the user:
```
ldapsearch -x -b ${LDAP_ROOT} -D "cn=${LDAP_ADMIN_USERNAME},${LDAP_ROOT}" -W -H ldap://127.0.0.1:1389
```

Take note of their `userPassword` field. Now repeat these steps with the latest debian10 container (bitnami/openldap:2.6.2-debian-10-r29) and note the `userPassword` field.

### What is the expected behavior?

The `userPassword` field should be a base64 encoded SHA-512 hash prefixed with `{CRYPT}$6$rounds=150000`.

### What do you see instead?

With the above example, the userPassword field is a base64 encoded `{CRYPT}*0` no matter what you set the password to. It is not possible to set the password in a way which stores it as SHA-512.

### Additional information

This appears to be due to a difference between the debian10 and debian11 containers as using the same openldap version (2.6.2) between the debian10 and debian11 containers produces different results. I thought perhaps a package was not installed in debian11 that is installed in debian10, but that does not appear to be the case.

**Comment by fmulero** [comment]
Hi @bamhm182 

I reproduced your issue and everything points to crypt error setting the password. As you mentioned the issue could be related to a missing package in debian 11. At the moment I couldn't find it so any clue is welcome

**Comment by fmulero** [comment]
Hi @bamhm182 

I think `olcPasswordCryptSaltFormat: $6$rounds=150000%.16s` is wrong. The format supported by `crypt` is `$id$rounds=yyy$salt$encrypted` (more details [here](https://manpages.debian.org/buster/manpages-dev/crypt.3.en.html#Features_in_glibc)), so the configuration for openladap should be `olcPasswordCryptSaltFormat: $6$rounds=150000$%.16s`. In debian 10 your configuration "works" but the password has an incorrect format (there is no salt part), for example:
```
{CRYPT}$6$rounds=150000XUY$Lh4Amv2C4Hfb5j.b/BB3huCZFPKExLVpay8GIGP5JuSZSzdbt21r6Y.VH7t9vA7Pxu27SGH3Byq9rrt0Arxp2.
```

How was it working? no idea
