### ISSUE TITLE
cannot import custom schema before populating tree

### ISSUE THREAD

**Issue by estoleru** [bitnami/bitnami-docker-openldap#111]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

I'm using docker desktop v2.1.0.1 on a windows10 machine disconnected from the internet.
I'm using an internal docker registry mirroring public repositories.
I'm trying to bootstrap a container of bitnami/openldap:2.6 image with a custom schema in which I define 2 attributes and 2 classes.
Steps to reproduce the bug:
1. `docker build --tag "spl-ldap" . -f Dockerfile_spl`
2. `docker-compose.exe -f .\docker-compose_spl.yml up -d`
[spl-ldap-20220622.zip](https://github.com/bitnami/bitnami-docker-openldap/files/8958128/spl-ldap-20220622.zip)

### What is the expected behavior?

Container running and the custom attributes and objectClasses are available for further usage.

### What do you see instead?
```
 16:10:05.14 INFO  ==> ** Starting LDAP setup **
 16:10:05.16 INFO  ==> Validating settings in LDAP_* env vars
 16:10:05.17 INFO  ==> Initializing OpenLDAP...
 16:10:05.17 DEBUG ==> Ensuring expected directories/files exist...
 16:10:05.18 INFO  ==> Creating LDAP online configuration
 16:10:05.20 INFO  ==> Starting OpenLDAP server in background
 16:10:05.22 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=50000,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

modifying entry "olcDatabase={0}config,cn=config"

modifying entry "olcDatabase={0}config,cn=config"

 16:10:05.22 INFO  ==> Adding LDAP extra schemas
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=50000,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=cosine,cn=schema,cn=config"

SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=50000,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=inetorgperson,cn=schema,cn=config"

SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=50000,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=nis,cn=schema,cn=config"

 16:10:05.24 INFO  ==> Adding custom Schema : /schema/99user.ldif ...
olcAttributeTypes: value #0 olcAttributeTypes: Unexpected token before  )
AttributeTypeDescription = "(" whsp
  numericoid whsp      ; AttributeType identifier
  [ "NAME" qdescrs ]             ; name used in AttributeType
  [ "DESC" qdstring ]            ; description
  [ "OBSOLETE" whsp ]
  [ "SUP" woid ]                 ; derived from this other
                                   ; AttributeType
  [ "EQUALITY" woid ]            ; Matching Rule name
  [ "ORDERING" woid ]            ; Matching Rule name
  [ "SUBSTR" woid ]              ; Matching Rule name
  [ "SYNTAX" whsp noidlen whsp ] ; see section 4.3
  [ "SINGLE-VALUE" whsp ]        ; default multi-valued
  [ "COLLECTIVE" whsp ]          ; default not collective
  [ "NO-USER-MODIFICATION" whsp ]; default user modifiable
  [ "USAGE" whsp AttributeUsage ]; default userApplications
                                   ; userApplications
                                   ; directoryOperation
                                   ; distributedOperation
                                   ; dSAOperation
  whsp ")"
slapadd: could not add entry dn="cn={4}ebusiness,cn=schema,cn=config" (line=1): olcAttributeTypes: Unexpected token before  )
```
[spl-ldap.log](https://github.com/bitnami/bitnami-docker-openldap/files/8958130/spl-ldap.log)

### Additional information

I didn't find anything reasonable for this error, one sample of LDIF file used for custom schema bootstrapping looks similar to spl_custom_schema.ldif (reference https://github.com/bitnami/bitnami-docker-openldap/issues/29).

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami openldap container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by estoleru** [comment]
I tried to find any posts on forums or user guides working samples for bootstrapping schema attributes or objectclasses, but no success.
I will add that the issue is reproducing also on my home desktop, using Docker Desktop v4.9.1
