### ISSUE TITLE
Make sizelimit and timelimit configurable

### ISSUE THREAD

**Issue by sassdavid** [bitnami/bitnami-docker-openldap#112]
### Name and Version

bitnami/openldap:latest

### What is the problem this feature will solve?

I would like to configure the sizelimit (and maybe the timelimit) properties based on this: https://www.openldap.org/doc/admin26/limits.html

I did not find possible solution with the current configuration possibilities.

### What is the feature you are proposing to solve the problem?

Maybe you could extend the set of the environment variables with 2 new variables:
LDAP_SIZE_LIMIT
LDAP_TIME_LIMIT
in order to being configurable these properties.

**Comment by sassdavid** [comment]
Sorry I accidentally closed and reopened this issue...

It is still an open question/request

**Comment by rafariossaa** [comment]
Hi,
  You are getting that error because ldap server is stopped when it reach the point of running user scripts.
  However, you can start it and run what you need. To start it, add to your script the following:
```
. /opt/bitnami/scripts/libopenldap.sh

ldap_start_bg
...
actions you want to perform
...
ldap_stop
```

**Comment by sassdavid** [comment]
Hi,

great, thank you for the suggestion, in this way it works correctly, the script was able to run without error.

Probably they did not assume that some user scripts require a running LDAP to run.

Thank you again for helping me to make my workaround work.

**Comment by rafariossaa** [comment]
You are welcome.
I am glad it worked for you. Thanks you for coming back.
