### ISSUE TITLE
[bitnami-docker-openldap] Replication Memory Leak

### ISSUE THREAD

**Issue by queueburt** [bitnami/bitnami-docker-openldap#114]
### Name and Version

bitnami/bitnami-docker-openldap:2.6.1

### What steps will reproduce the bug?

All settings remain standard besides multi-master replication being turned on with [OLC syncprov](https://www.openldap.org/doc/admin26/replication.html).

### What is the expected behavior?

Replication functions as expected and memory utilization stabilizes as queries populate the tree in memory.

### What do you see instead?

Replication functions as expected for both OLC and primary trees, but memory usage on all instances slowly increase until all instances crash to OOM errors.  Restarting the instances resolves the failures.
![Screen Shot 2022-07-05 at 11 17 52 AM](https://user-images.githubusercontent.com/19719453/177390891-5c5493e5-35e0-4931-88ee-317a3fa743bb.png)

### Additional information

This may be an issue with OpenLDAP in general, as there are a number of unresolved list entires online regarding memory utilization with SLAPD that look remarkably similar:

https://phabricator.wikimedia.org/T130593
https://www.openldap.org/lists/openldap-technical/201509/msg00059.html
https://openldap-technical.openldap.narkive.com/eEBLeHjr/openldap-replication-memory-leak

Many of these deal with ~2.4, however, and make some generalized recommendations to replace the memory allocator with TCMalloc, but given that this environment is on Kubernetes, specialty Linux configuration is impractical.

**Comment by rafariossaa** [comment]
Hi,
  This seems to be an upstream issue. We use the standard compilation from openldap. 
  Maybe you want to report them your use case so they can fix the memory leak.
