### ISSUE TITLE
ARM64 container images for OpenLDAP

### ISSUE THREAD

**Issue by Shanduur** [bitnami/bitnami-docker-openldap#115]
### Name and Version

bitnami/openldap:latest

### What is the problem this feature will solve?

Availability of OpenLDAP on other systems than `amd64`.

### What is the feature you are proposing to solve the problem?

Now the image built targets only the classic `amd64` platform. It is needed to provide this image for `arm64` platform in addition to the base. It could be built with use of `docker buildx`.

### What alternatives have you considered?

Separate tags for `arm64` images.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
