### ISSUE TITLE
Bootstrap LDAP schema from LDIF file

### ISSUE THREAD

**Issue by wiibaker** [bitnami/bitnami-docker-openldap#14]
**Description**

Related to issue #7 and the related PR #8 there would need also to load custom schema at the initialization phase ie. possibility bootstrap the LDAP with custom schema.

**Describe the results you received:**

The loading of custom LDIF files which have custom schema elements fail

**Describe the results you expected:**

Custom schema files are loaded at initial boot.

Loading the custom LDIF files with custom schema elements succeed.

**Comment by wiibaker** [comment]
I could try creating a PR for this on similar pattern as in #8

**Comment by dani8art** [comment]
Hi @wiibaker thanks for the feedback

>There is issue if you have multiple files in the same directory and "find" does not guarantee the order of the files. You could do this which would be at least more reliable
> `for f in $LDAP_CUSTOM_LDIF_DIR/*.ldif; do ldapadd -H 'ldapi:///' -D "$LDAP_ADMIN_DN" -w "$LDAP_ADMIN_PASSWORD" -f $f; done`
>This should work if you have files named like "01-file.ldif, 02-file.ldif" or other natural order.

I think this would be a good approach to fix your issue, would you like to open a PR adding this fix so we can incorporate this into the image?

**Comment by wiibaker** [comment]
@dani8art I guess that comment should have gone into #8 right?

**Comment by andresbono** [comment]
> I guess that comment should have gone into #8 right?

I see you sorted it out, right @wiibaker?

> I could try creating a PR for this on similar pattern as in #8

That would be great!! 🎉
