### ISSUE TITLE
MemberOf support 

### ISSUE THREAD

**Issue by Stromboy** [bitnami/bitnami-docker-openldap#17]
HI Team I am a huge fan of your images, :) 

however, I am trying to enable Member Of to support your docker container but I seem to be having issues finding the right input, and I was hoping you may offer some insight.

I am using the following tutorial to move through this 
brianshowalter.com/blog/installing-configuring-openldap

-------------------------------
INFORMATION REQUEST
-------------------------------
etc/default/slapd where is this mapped location 

below is from turoral
cat > /etc/ldap/backend.memberof.ldif <<EOT
dn: cn=module,cn=config
cn: module
objectClass: olcModuleList
objectClass: top
olcModulePath: /usr/lib/ldap
olcModuleLoad: memberof.la
 
dn: olcOverlay={0}memberof,olcDatabase={1}hdb,cn=config
objectClass: olcConfig
objectClass: olcMemberOf
objectClass: olcOverlayConfig
objectClass: top
olcOverlay: memberof
EOT

do you happen to know the correct path for olcModulePath to allow this to complete? 

Thank you for your time, if you happen to have your own documentation on I would really appreciate it 

Thank you for the great products and I hope to hear back from you.

**Comment by dani8art** [comment]
Hi @Stromboy 

Regarding ldif, you can use `LDAP_CUSTOM_LDIF_DIR` from https://github.com/bitnami/bitnami-docker-openldap#configuration to point to where you create this file. 

Regarding olcModulePath, you can find it here:

```
$ docker run --rm -ti bitnami/openldap -- ls /opt/bitnami/openldap/lib/openldap/
```

**Comment by Stromboy** [comment]
wonderful thank you for your fast help :D

**Comment by dani8art** [comment]
yw! don't hesitate to contact us if you find any other issue!
