### ISSUE TITLE
Multi-arch docker images for arm64

### ISSUE THREAD

**Issue by cjyar** [bitnami/bitnami-docker-openldap#18]
**Description**

Would it be possible to produce multi-arch docker images that include arm64?

**Steps to reproduce the issue:**

1. Try to run `bitnami/openldap:2.4.56` on arm64.

**Describe the results you received:**

Container logs:
```
standard_init_linux.go:219: exec user process caused: exec format error
```

**Describe the results you expected:**

The program in the container should run.

**Comment by dani8art** [comment]
Hi @cjyar thanks for opening this issue, we are currently exploring the possibility to include this feature in our catalog, however, due to the fact that we are a small team and taking into account internal milestone, we have no idea when it is going to happen so we can't give you an ETA. 

Thanks, we will keep you updated.

**Comment by dkowis** [comment]
I don't think I can re-open this, but do you have any other images that are multi-arch? I see that the binami/minideb does build an arm64 version, just looking for an example of how it's used.

**Comment by carrodher** [comment]
Hi, unfortunately at this moment bitnami/minideb is the only image supporting arm64. This image is the base image used in the rest of the containers so it was the first step, but still, there are several tasks we should work on before supporting this architecture in the whole catalog.

Apart from that, we created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversations in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
