### ISSUE TITLE
custom db bootstrap broken

### ISSUE THREAD

**Issue by kurt-hectic** [bitnami/bitnami-docker-openldap#19]
**Description**

Custom ldif files contained in LDAP_CUSTOM_LDIF_DIR are not considered with debian-10-r20 .
The build before the last commit that did a change to the custom ldif command LDAP_CUSTOM_LDIF_DIR works ok.

**Steps to reproduce the issue:**

1. copy tree.ldif file from container started without LDAP_CUSTOM_LDIF_DIR into directory
2. mount this directly into container (e.g /ldifs) as docker volume
3. docker-compose up

**Describe the results you received:**

Container is built and started, I can see the "skipping LDAP_USERS etc" message.
But the custom ldap files are not imported. 
```ldapsearch -h 127.0.0.1 -p 1389 -x "(objectClass=*)"```  produces nothing.

**Describe the results you expected:**

```ldapsearch -h 127.0.0.1 -p 1389 -x "(objectClass=*)"```  should show the contents of my custom ldif file

**Additional information you deem important (e.g. issue happens only occasionally):**

If I take a previous build (from before a recent change to the custom ldif procedure), the custom ldfi file is imported ok.

**Version**

Docker 2.5.0 on Windows 10

**Comment by andresbono** [comment]
Hi @kurt-hectic, what is the commit you suspect that introduced the bug? Is this one? https://github.com/bitnami/bitnami-docker-openldap/commit/95675d35fad03eea7b0166b92f0a5e69bc0194c7

**Comment by jason-matthew** [comment]
I believe issue here stems from shell pipe used within ldap_add_custom_ldifs. 
https://github.com/bitnami/bitnami-docker-openldap/blob/cf75d369023c7c883af4ec3cc1248c94861c2fab/2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L311

enabling `BITNAMI_DEBUG` allows for successful execution.

**Comment by rafariossaa** [comment]
Waiting for https://github.com/bitnami/bitnami-docker-openldap/pull/20

**Comment by rafariossaa** [comment]
Hi,
  #20 was merged, did you have a chance to test it ?.
