### ISSUE TITLE
LDAP_TLS_ENABLED vs LDAP_ENABLE_TLS

### ISSUE THREAD

**Issue by aeisma** [bitnami/bitnami-docker-openldap#23]
LDAP_TLS_ENABLED=yes did not enable ldaps in the 2.4.57-debian-10-r0 release.

I inspected the scripts, and found references to LDAP_ENABLE_TLS.
TLS started working after adding adding LDAP_ENABLE_TLS=yes to the environment.

**Comment by carrodher** [comment]
Hi, thanks for reporting the issue, it seems the env. variable is not properly documented in the README. The one used by the image is `LDAP_ENABLE_TLS` while the one documented in the README is `LDAP_TLS_ENABLED`. I will create a PR addressing the issue. Thanks!

**Comment by TimLovesTech** [comment]
Can this be updated on the Docker hub page as well? Thanks!
https://hub.docker.com/r/bitnami/openldap/

**Comment by carrodher** [comment]
Done! thanks
