### ISSUE TITLE
Group member is corrupted when specifying multiple users

### ISSUE THREAD

**Issue by jamshid** [bitnami/bitnami-docker-openldap#27]
Specifying multiple users in LDAP_USERS, simply using the exact docker-compose.yml you show on docker hub, creates a corrupt `member` attribute for the group.

**Steps to reproduce the issue:**

1. Copy the docker-compose.yml from https://hub.docker.com/r/bitnami/openldap
2. docker-compose up -d
3. See the users are created as expected but the group member is all wrong. 
```
curl 'ldap://192.168.1.50:1389/dc=example,dc=org?*?sub?(objectclass=*)'
...
DN: cn=user01,ou=users,dc=example,dc=org
...
DN: cn=user02,ou=users,dc=example,dc=org
...
DN: cn=readers,ou=users,dc=example,dc=org
	cn: readers

	objectClass: groupOfNames

	member: cn=user01 cn\3Duser02,ou=users,dc=example,dc=org
```

**Describe the results you received:**

above

**Describe the results you expected:**

```
DN: cn=readers,ou=users,dc=example,dc=org
	cn: readers

	objectClass: groupOfNames

	member: cn=user01,ou=users,dc=example,dc=org
	member: cn=user02,ou=users,dc=example,dc=org
```

**Version**

- Output of `docker version`:

```
20.10.2 Docker for Mac
```

- Output of `docker-compose version` (if applicable):

```
docker-compose 1.27.4
```

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. Maybe it makes sense to use ldapmodify to add the members, thoughts on that? 

https://www.thegeekstuff.com/2015/02/openldap-add-users-groups/

**Comment by jamshid** [comment]
Yes it can be corrected manually with ldapmodify or other tools but this issue was filed to make the automated setup of the container create members correctly.

**Comment by javsalgar** [comment]
Hi,

Yes, I meant changing the logic to use this command instead of creating the file as it currently is. I just wanted to confirm that this could be the way to go.
