### ISSUE TITLE
Unable to load data using LDIF

### ISSUE THREAD

**Issue by anupam688** [bitnami/bitnami-docker-openldap#28]
Hi Team ,
LDIF file shows as loaded but tree is not created .

# Docker file
FROM bitnami/openldap:2.4.56-debian-10-r56
ENV LDAP_ADMIN_USERNAME=admin \
    LDAP_ADMIN_PASSWORD=adminpassword \
    LDAP_ROOT="dc=hbk,dc=xyz" \
    LDAP_CUSTOM_LDIF_DIR="/bitnami"
COPY bootstrap.ldif /bitnami/ldifs/bootstrap.ldif 

# bootstrap.ldif 

dn: dc=hbk,dc=xyz
objectClass: dcObject
objectClass: organization
dc: hbk
o: example

dn: ou=users,dc=hbk,dc=xyz
objectClass: organizationalUnit
ou: users

dn: cn=user01,ou=users,dc=hbk,dc=xyz
cn: User1
sn: Bar1
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
userPassword: bitnami1
uid: user01
uidNumber: 1000
gidNumber: 1000
homeDirectory: /home/user01

dn: cn=user02,ou=users,dc=hbk,dc=xyz
cn: User2
sn: Bar2
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
userPassword: bitnami2
uid: user02
uidNumber: 1001
gidNumber: 1001
homeDirectory: /home/user02

dn: cn=readers,ou=users,dc=hbk,dc=xyz
cn: readers
objectClass: groupOfNames
member: cn=user01 cn=user02,ou=users,dc=hbk,dc=xyz

# Test Result
With docker run i get below output 
 23:18:47.08 INFO  ==> ** Starting LDAP setup **
 23:18:47.11 INFO  ==> Validating settings in LDAP_* env vars
 23:18:47.13 INFO  ==> Initializing OpenLDAP...
 23:18:47.15 INFO  ==> Creating LDAP online configuration
 23:18:47.17 INFO  ==> Starting OpenLDAP server in background
 23:18:48.72 INFO  ==> Configure LDAP credentials for admin user
 23:18:48.79 INFO  ==> Adding LDAP extra schemas
 23:18:48.83 INFO  ==> Loading custom LDIF files...
 23:18:48.84 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
 23:18:48.87 INFO  ==> ** LDAP setup finished! **

 23:18:48.92 INFO  ==> ** Starting slapd **
602c52d8 @(#) $OpenLDAP: slapd 2.4.56 (Nov 11 2020 03:09:45) $
        @3ccbe9810b42:/bitnami/blacksmith-sandox/openldap-2.4.56/servers/slapd

But when i do ldap search results in below
ldapsearch -H "ldapi:///" -D cn=admin,dc=hbk,dc=xyz-w adminpassword -b "dc=hbk,dc=xyz"
 extended LDIF

 LDAPv3
 base <dc=hbk,dc=xyz> with scope subtree
 filter: (objectclass=*)
 requesting: ALL

 search result
search: 2
result: 32 No such object

 numResponses: 1
I have no name!@8004ecd8ed00:/$

Please let me know if I am doing something wrong

**Comment by marcosbc** [comment]
Hi @anupam688, currently OpenLDAP requires LDIF files to be located in the folder you specified in `LDAP_CUSTOM_LDIF_DIR` directly, it cannot be in a subfoldr. Since you specified `/bitnami` you should locate the .ldif file there, not in `/bitnami/ldifs`.

**Comment by anupam688** [comment]
Hi @marcosbc 

Thanks for your comment worked out like charm.
