### ISSUE TITLE
--enable-modules flag

### ISSUE THREAD

**Issue by germantraut** [bitnami/bitnami-docker-openldap#30]
Hello,
you are doing great work here!

It is my first time using LDAP.
I am looking to add backend modules. But i don't understand where i have to set the --enable-modules flag.
As far as i undestood it has to be set while building from source with ./configure -flags.
Is it possible to set this flag? Or do i have to compile LDAP from source?

Best regards

**Comment by miguelaeh** [comment]
Hi @germantraut ,
Our OpenLDAP has been compiled with that flag enabled so you shouldn't have the need of change anything

**Comment by germantraut** [comment]
Hey,
thanks for the fast answer.
i don't understand why i can't load a module then.

**Steps to reproduce the issue:**

1. Starting the image
2. executing this ldif:
dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModuleLoad: /usr/lib/ldap/ppolicy.la


**Describe the results you received:**

getting this error for it:
MOD dn="cn=module{0},cn=config"
conn=1019 op=12 MOD attr=olcModuleLoad
lt_dlopenext failed: (/usr/lib64/openldap/ppolicy.la) file not found
RESULT tag=103 err=80 text=<olcModuleLoad> handler exited with 1

while:
/usr/lib64/openldap/ppolicy.la
exists and has proper permissions. Also checked permissions for dirs. I tripple checked this.


**Describe the results you expected:**

ppolicy.la get's loaded and is in dn="cn=module{0},cn=config".

**Additional information you deem important (e.g. issue happens only occasionally):**

ldapadd:
dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModulePath: /usr/lib64/openldap/

works fine. Just the module doesn't want to load...




**Version**
bitnami/openldap:2.4.57

- Output of `docker version`:

```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 122
  Running: 100
  Paused: 0
  Stopped: 22
 Images: 27
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 50GiB
 Name: docker-desktop
 ID: SHFI:KNWH:XPSS:4CBE:RSOA:N3EV:NLSN:PBYY:NY7U:OKUZ:S6YK:5WB5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `kubectl version` (if important):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes Rancher

**Comment by miguelaeh** [comment]
Hi @germantraut ,
have you tried setting into `olcModuleLoad` the module name and also setting the `olcModulePath`?
You can find an example here https://www.openldap.org/doc/admin24/slapdconf2.html
Also the LDAP error code can be found here: https://ldapwiki.com/wiki/LDAP%20Result%20Codes

You can also try to place the module into another path

**Comment by germantraut** [comment]
Hi @miguelaeh,
yeah i tried to seperate olcModuleLoad and olcModulePath, same result.
Also tried to place the modules in another path.
The documentation is why i thought to enable the modules with the flags first.
Thanks for the ldap wiki, didn't know about that. But the error code is 80 it is a generic one (LDAP_OTHER).

**Comment by marcosbc** [comment]
Hi @germantraut, in your previous post I could see this:

```
olcModuleLoad: /usr/lib/ldap/ppolicy.la
...
olcModulePath: /usr/lib64/openldap/
```

It's clear by the error that what's failing is the `olcModulePath`:

```
 lt_dlopenext failed: (/usr/lib64/openldap/ppolicy.la) file not found
```

And note that `/usr/lib64/openldap` is not created by default in the container image:

```
$ docker run -ti bitnami/openldap ls -la /usr/lib64/openldap/
ls: cannot access '/usr/lib64/openldap/': No such file or directory
```

So I would say you are either not mounting that directory properly, or you are using the wrong `olcModulePath`.

If you continue to find issues after reviewing your Docker deployment setup, please describe further how you deployed your solution including all environment variables, mounted files and so. I.e. providing a docker-compose file.

**Comment by germantraut** [comment]
Loading the ppolicy module worked for me with this ldif.
No path no suffix. No clue why so.

dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModuleLoad: ppolicy
