### ISSUE TITLE
Use mdb (LMDB) instead of HDB (Berkeley DB)

### ISSUE THREAD

**Issue by yonas** [bitnami/bitnami-docker-openldap#32]
It would be great if this Docker image used the mush faster mdb.

[osixia/docker-openldap](https://github.com/osixia/docker-openldap) seem to already be using mdb.

**Comment by marcosbc** [comment]
Hi @yonas, the scripts are open sourced, so feel free to check any required changes for adding mdb support: https://github.com/bitnami/bitnami-docker-openldap/tree/master/2/debian-10

If you are able to get it working, you can send a PR, we'd be glad to review and help with the release process.
