### ISSUE TITLE
Not able to start using persisted data

### ISSUE THREAD

**Issue by Fareroo7** [bitnami/bitnami-docker-openldap#38]
**Description**

As soon as I mount a volume to persist data openLDAP server is not able to start.
Without the volume mount, it works just fine.

I am running this on a kubernetes cluster.

**Steps to reproduce the issue:**

1. kubectl apply -f openldap.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: "/opt/bitnami/openldap/certs/tls.crt"
            - name: LDAP_TLS_KEY_FILE
              value: "/opt/bitnami/openldap/certs/tls.key"
            - name: LDAP_TLS_CA_FILE
              value: "/opt/bitnami/openldap/certs/ca.crt"
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  key: users
                  name: openldap
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  key: passwords
                  name: openldap
          ports:
            - name: tcp-ldap
              containerPort: 1389
            - name: tcp-ldaps
              containerPort: 1636
          volumeMounts:
            - name: certs
              mountPath: "/opt/bitnami/openldap/certs"
            - name: data
              mountPath: "/bitnami/openldap/data"
      volumes:
        - name: certs
          secret:
            secretName: ldap-tls-secret
        - name: data
          persistentVolumeClaim:
            claimName: openldap-pvc
```

**Describe the results you received:**

In the logs I get:
```
 12:39:42.05 INFO  ==> ** Starting LDAP setup **
 12:39:42.08 INFO  ==> Validating settings in LDAP_* env vars
 12:39:42.10 INFO  ==> Initializing OpenLDAP...
 12:39:42.12 INFO  ==> Using persisted data
 12:39:42.12 INFO  ==> ** LDAP setup finished! **

 12:39:42.15 INFO  ==> ** Starting slapd **
60bf650e @(#) $OpenLDAP: slapd 2.4.58 (Mar 17 2021 00:19:19) $
        @0a164ab8b404:/bitnami/blacksmith-sandox/openldap-2.4.58/servers/slapd
60bf650e slapd stopped.
60bf650e connections_destroy: nothing to destroy.
```

**Describe the results you expected:**

When I remove the volume mount for /bitnami/openldap/data it works as expected.
```
 12:53:11.63 INFO  ==> ** Starting LDAP setup **
 12:53:11.65 INFO  ==> Validating settings in LDAP_* env vars
 12:53:11.67 INFO  ==> Initializing OpenLDAP...
 12:53:11.69 INFO  ==> Creating LDAP online configuration
 12:53:11.72 INFO  ==> Starting OpenLDAP server in background
 12:53:11.75 INFO  ==> Configure LDAP credentials for admin user
 12:53:11.77 INFO  ==> Configuring TLS
 12:53:11.78 INFO  ==> Adding LDAP extra schemas
 12:53:11.81 INFO  ==> Creating LDAP default tree
 12:53:13.02 INFO  ==> ** LDAP setup finished! **

 12:53:13.04 INFO  ==> ** Starting slapd **
60bf6839 @(#) $OpenLDAP: slapd 2.4.58 (Mar 17 2021 00:19:19) $
        @0a164ab8b404:/bitnami/blacksmith-sandox/openldap-2.4.58/servers/slapd
60bf6839 hdb_db_open: warning - no DB_CONFIG file found in directory /bitnami/openldap/data: (2).
Expect poor performance for suffix "dc=example,dc=org".
60bf6839 slapd starting
```

**Comment by Mauraza** [comment]
Hi @Fareroo7,

could you change the `mountPath` of data and try again?
```yaml
 volumeMounts:
            - name: certs
              mountPath: "/opt/bitnami/openldap/certs"
            - name: data
              mountPath: "/bitnami/openldap/data"
```
to 
```
 volumeMounts:
            - name: certs
              mountPath: "/opt/bitnami/openldap/certs"
            - name: data
              mountPath: "/bitnami/openldap"
```

**Comment by Fareroo7** [comment]
Hello @Mauraza,

sure!
I changed it and it still not able to start the LDAP service.
But the log is different:

```
 11:03:20.91 INFO  ==> ** Starting LDAP setup **
 11:03:20.93 INFO  ==> Validating settings in LDAP_* env vars
 11:03:20.95 INFO  ==> Initializing OpenLDAP...
 11:03:20.97 INFO  ==> Using persisted data
 11:03:20.97 INFO  ==> ** LDAP setup finished! **

 11:03:21.00 INFO  ==> ** Starting slapd **
60c09ff9 @(#) $OpenLDAP: slapd 2.4.58 (Mar 17 2021 00:19:19) $
        @0a164ab8b404:/bitnami/blacksmith-sandox/openldap-2.4.58/servers/slapd
60c09ffc hdb_db_open: database "dc=my-domain,dc=com": alock package is unstable.
60c09ffc backend_startup_one (type=hdb, suffix="dc=my-domain,dc=com"): bi_db_open failed! (-1)
60c09ffc slapd stopped.
```

**Comment by Mauraza** [comment]
Hi @Fareroo7,

There is an issue https://github.com/bitnami/bitnami-docker-openldap/issues/1, could you check you are running the last version of OpenLDAP?

**Comment by Fareroo7** [comment]
Hi,

yes, I'm running the latest version of OpenLDAP.
Started once with the 2.4.58-debian-10-r71 tag and once with the latest tag.
Still getting the same error.

**Comment by Mauraza** [comment]
Hi @Fareroo7,

There already an internal task to investigate. We will update these threads when we have more information.

**Comment by Fareroo7** [comment]
Hi @Mauraza,

thank you!
Let me know if you need any additional information or testing to be done.

**Comment by Fareroo7** [comment]
Hi,

I found the issue.
The was a problem with the volume provisioning, not in the image.

**Comment by BLKFSH** [comment]
Hey!
I'm facing the same issue, however I'm not using Kubernetes, just Docker. When creating a container that uses persistent data (both using a volume and a path on the host), the container starts, but when it tries starting slapd I simply get the following message and the container stops:
```
 01:46:04.22 INFO  ==> ** Starting slapd **
61ca6c5c.0dbde88c 0x7f32f2246080 @(#) $OpenLDAP: slapd 2.5.9 (Oct 26 2021 00:15:05) $
	@0959acab74d6:/bitnami/blacksmith-sandox/openldap-2.5.9/servers/slapd
61ca6c5c.0dffdb01 0x7f32f2246080 slapd stopped.
61ca6c5c.0e01163c 0x7f32f2246080 connections_destroy: nothing to destroy.
```
My steps to reproduce this are as follows:

1. `docker volume create openldap` & `docker network create ldap-network`
2. `docker run -d --name openldap --restart unless-stopped --network ldap-network  -e LDAP_ROOT="dc=domain,dc=com" -e LDAP_ADMIN_USERNAME=admin -e LDAP_ADMIN_PASSWORD="password"  -e BITNAMI_DEBUG=1 -v openldap:/bitnami/openldap/data bitnami/openldap:latest`
3. `docker container stop openldap` & `docker container rm openldap`
4. Run command from step 2 again

What am I doing wrong here? Thanks in advance! :)

**Comment by Mauraza** [comment]
Hi @BLKFSH,

Did you check this comment https://github.com/bitnami/bitnami-docker-openldap/issues/38#issuecomment-858380379 ??

**Comment by BLKFSH** [comment]
Hey @Mauraza , thanks for the quick reply!
I have checked this comment and I am on the newest version of this container. As for issue #1 I have checked that as well but if I understand correctly it's still unknown why this happens?
I'm just a little confused because I was unable to find a clear answer on why this happens and there haven't been many news in these threads.

**Comment by Mauraza** [comment]
Hi @BLKFSH,

Could you share the logs of the first run (with a new volume)?

**Comment by BLKFSH** [comment]
Sure! These are with `BITNAMI_DEBUG=1`

```
 01:42:50.78 INFO  ==> ** Starting LDAP setup **
 01:42:50.84 INFO  ==> Validating settings in LDAP_* env vars
 01:42:50.86 INFO  ==> Initializing OpenLDAP...
 01:42:50.87 DEBUG ==> Ensuring expected directories/files exist...
 01:42:50.89 INFO  ==> Creating LDAP online configuration
 01:42:50.92 INFO  ==> Starting OpenLDAP server in background
 01:42:50.95 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

 01:42:50.97 INFO  ==> Adding LDAP extra schemas
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=cosine,cn=schema,cn=config"

SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=inetorgperson,cn=schema,cn=config"

SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=nis,cn=schema,cn=config"

 01:42:51.00 INFO  ==> Creating LDAP default tree
adding new entry "dc=domain,dc=com"

adding new entry "ou=users,dc=domain,dc=com"

adding new entry "cn=user01,ou=users,dc=domain,dc=com"

adding new entry "cn=user02,ou=users,dc=domain,dc=com"

adding new entry "cn=readers,ou=users,dc=domain,dc=com"

 01:42:52.08 INFO  ==> ** LDAP setup finished! **

 01:42:52.12 INFO  ==> ** Starting slapd **
61cd0e9c.07ee334e 0x7f44560f3080 @(#) $OpenLDAP: slapd 2.5.9 (Oct 26 2021 00:15:05) $
	@0959acab74d6:/bitnami/blacksmith-sandox/openldap-2.5.9/servers/slapd
61cd0e9c.08b645b5 0x7f44560f3080 slapd starting
```

**Comment by Mauraza** [comment]
Hi @BLKFSH,

Did you connect OpenLDAP with any app?

**Comment by BLKFSH** [comment]
Hey @Mauraza !
I connected it to a bitnami/dokuwiki instance and a bitnami/phabricator instance and those are working fine. For managing the LDAP tree I'm using a dockerized version of ldap-account-manager.
The openldap container only starts acting up if I delete and run it again, stopping and starting it is no issue at all.

**Comment by Mauraza** [comment]
Hi @BLKFSH,

I think to create a new container of OpenLDAP you need to delete the volume to start a new container. Like appears in https://github.com/bitnami/bitnami-docker-openldap#upgrade-this-image

**Comment by BLKFSH** [comment]
Hey @Mauraza ,
but `docker rm -v` only removes anonymous volumes. If I specify a volume with a name such as in https://github.com/bitnami/bitnami-docker-openldap#using-docker-compose then that won't be removed. Besides, aren't volumes there to separate important data from the rest of the container so it can be reused when for example upgrading the container? If data shouldn't be persisted then why create a volume in the first place?

**Comment by Mauraza** [comment]
Hi @BLKFSH,

could you try the same step but using this docker-compose.yaml?
```yaml
version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=domain,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - BITNAMI_DEBUG=true
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local
```

**Comment by colinm-omnifederal** [comment]
@BLKFSH I was having the same problem, but fixed it by setting the volume path to /bitnami/openldap instead of /bitnami/openldap/data. /bitnami/openldap/slapd.d also needs to be persisted.

**Comment by BLKFSH** [comment]
Sorry for the late reply @Mauraza,
I tried via docker compose and it does work, the solution is just as @colinm-omnifederal said. In the `docker run` script it mounts the volume to `/bitnami/openldap/data` while in the `docker-compose` one it specifies just `/bitnami/openldap`. Changing this in the `docker-run` script fixes this issue as well.
Thank you for the help everyone!  :)
