### ISSUE TITLE
Add automated DB+config backups

### ISSUE THREAD

**Issue by RogerSik** [bitnami/bitnami-docker-openldap#39]
Would be nice if this container would do daily backups of the config and database db in lidf format.

**Comment by juan131** [comment]
Hi @RogerSik 

Thanks so much for your suggestion! 

IMHO that use case shouldn't be targeted by this container itself, but instead a container you run in parallel that periodically creates the backups. For instance, if you're running the OpenLDAP container in Kubernetes, you could use a [K8s cronjob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to use a container that access the OpenLDAP server and creates the backups.

In any case, please note that this container code is open-source and available in this repository, please feel free to contribute a PR adding this functionality if you consider it important and our team will be glad to review it and help you with the process to include the changes in the container.
