### ISSUE TITLE
Does the current version support dual-master synchronization

### ISSUE THREAD

**Issue by willis0591** [bitnami/bitnami-docker-openldap#40]
Does the current version support dual-master synchronization? I don’t see the relevant variable parameters.I know that the osixia version of openladp supports dual main mode.

**Comment by rafariossaa** [comment]
Hi,
  Do you mind posting the issue in English ?
  That way more people can help and also find the issues and answers easier.

  Thanks forehand.

**Comment by willis0591** [comment]
Does the current version support dual-master synchronization? I don’t see the relevant variable parameters.I know that the osixia version of openladp supports dual main mode

**Comment by rafariossaa** [comment]
Hi  @willis0591,
  I am sorry, but no, the current image does not support this in the initialization logic. 
  However, if you wish you could use this image as base and set the configuration the initialization scripts.
