### ISSUE TITLE
How to configure TLS on bitnami-docker-openldap

### ISSUE THREAD

**Issue by ramankumarrudr** [bitnami/bitnami-docker-openldap#5]
How to configure TLS on bitnami-docker-openldap?

**Comment by FraPazGal** [comment]
Hi @ramankumarrudr,

At the moment, this container doesn't support TLS, but it is true that it would be a good feature to have. We cannot guarantee an ETA but we will be looking into this in the following days. We will update the ticket as soon as we have more news.

**Comment by stodge** [comment]
Any news? :)

**Comment by FraPazGal** [comment]
Hello @stodge,

I apologise, this got pushed back in our backlog and ended up going on-hold. We'll bump its priority and work on this as soon as possible so a new version is released. Thank you for your patience.

**Comment by stodge** [comment]
No need to apologise. :)

**Comment by sumidiot** [comment]
If it's helpful, I think I have made TLS work by hacking around a bit, as follows. I'll note that I am no expert in any of this, and clearly the below is not particularly clean.

In a `Dockerfile` `FROM` the bitnami image (2.4.56), I `COPY` in some cert files (e.g., to `/certs`), with `--chown 1001:1001`. I also `COPY` in modified versions of `run.sh` (to expose ldaps://) and `setup.sh` (to configure the tls options in openldap). I convince myself it's working as expected with `env LDAPTLS_CACERT=/certs/truststore.pem ldapsearch -x -b "dc=example,dc=org" -H ldaps://ldap:1636/ -D "cn=admin,dc=example,dc=org" -w adminpassword -LLL -Z` from inside the running instance - I see results come back, and the log for the server shows `TLS established` messages.

The change to `run.sh` is relatively small, adding `ldaps://:${LDAP_LDAPS_PORT_NUMBER}/` as one of the `-h` `flags` on [this line](https://github.com/bitnami/bitnami-docker-openldap/blob/bd36c573783b21987a1039b755132af34381a9fc/2/debian-10/rootfs/opt/bitnami/scripts/openldap/run.sh#L16).

The change to `setup.sh` is a little more involved. First, I have an ldif file that I `COPY` into the image, e.g., at `/certs/certs.ldif` (copy of this file below). Then, at the end of the `setup.sh` script, I want to run `ldapmodify -Y EXTERNAL -H ldapi:/// -f /certs/certs.ldif`. To do that, I have to make sure the server is started first (e.g., with `ldap_start_bg` coming from `libopenldap.sh`). However, the setup script is calling `ldap_initialize` before that, which shuts off the server, and I think there's some timing issue - if I `sleep 3s` before calling `ldap_start_bg`, it seems to go ok. After the `ldapmodify` line I also `ldap_stop`. So the end of `setup.sh` is basically:
```
sleep 3s
ldap_start_bg
ldapmodify -Y EXTERNAL -H ldapi:/// -f /certs/certs.ldif
ldap_stop
```

The `certs.ldif` file used for the `ldapmodify` call above is:
```
dn: cn=config
changetype: modify
add: olcTLSCACertificateFile
olcTLSCACertificateFile: /certs/truststore.pem
-
add: olcTLSCertificateFile
olcTLSCertificateFile: /certs/server.crt
-
add: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /certs/private.key
```

Thanks for the base image!

**Comment by FraPazGal** [comment]
Hello all,

Thank you for sharing your work and helping everyone, @sumidiot! 

We have released a [new version](https://github.com/bitnami/bitnami-docker-openldap/commit/ca7fc27fcf5a53ea4bdcf4475b6caf9382ed5b51) that adds TLS support for openldap. Could you confirm that your are able to configure it correctly on your end?

**Comment by sumidiot** [comment]
I've tried out the new version, and got it working as expected! Thanks, and sorry for the delay.

**Comment by javsalgar** [comment]
Great! Don't hesitate to  open a new ticket if you find any other issue
