### ISSUE TITLE
Unable to modify LDAP configuration with ldapmodify

### ISSUE THREAD

**Issue by aintbrokedontfix** [bitnami/bitnami-docker-openldap#53]
Can ldapmodify be used to make changes? I tried the following as is and using the default password for LDAP_CONFIG_ADMIN_PASSWORD, but it does not work. 

```
ldapmodify -H ldap://{{ hostname }}:1389 -x -W -D 'cn=config' -f custom-ldif/mdb-db-max-size.ldif
Enter LDAP Password:
```

Thanks!

**Comment by rafariossaa** [comment]
Hi,
  Did you get any error when running it ? Could you share the `.ldif` you are trying to load ?

**Comment by aintbrokedontfix** [comment]
@rafariossaam,
The ldif looks like this.

```
dn: olcDatabase={2}mdb,cn=config
changeType: modify
add: olcDbMaxSize
olcDbMaxSize: 2000000000
```

**Comment by rafariossaa** [comment]
Hi, 
  Could you try by enabling `LDAP_CONFIG_ADMIN_ENABLED` ? 
  The user does not have enough permission to be able to do that modification at this stage.

**Comment by aintbrokedontfix** [comment]
Hi @rafariossaa,

This is the config I used to deploy the image when I got the error. I am wondering if I was missing something in the bind dn (-D) in ldapmodify? 

```
docker run --name my-ldap -p 1389:1389/tcp \
    -v /opt/bitnami/ldap/data:/bitnami/openldap/data \
    -v /opt/bitnami/ldap/slapd.d:/bitnami/openldap/slapd.d \
    -e LDAP_ROOT=dc=my,dc=domain,dc=com \
    -e LDAP_ADMIN_USERNAME=admin \
    -e LDAP_ADMIN_PASSWORD=*** \
    -e LDAP_CONFIG_ADMIN_ENABLED=yes \
    -e LDAP_CONFIG_ADMIN_USERNAME=config \
    -e LDAP_CONFIG_ADMIN_PASSWORD=*** \
    -e LDAP_USER_DC=People \
    -e LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis \
    -e LDAP_CUSTOM_SCHEMA_FILE=/opt/bitnami/ldap/custom-ldif \
    -e BITNAMI_DEBUG=true \
    bitnami/openldap:2.5 
```

**Comment by rafariossaa** [comment]
Hi,
  I started LDAP with:
```
$ docker run --name ldap \
 -e LDAP_ADMIN_USERNAME=admin \
 -e LDAP_ADMIN_PASSWORD=testpwd \
 -e LDAP_CONFIG_ADMIN_ENABLED=yes \
 -e LDAP_CONFIG_ADMIN_USERNAME=config \
 -e LDAP_CONFIG_ADMIN_PASSWORD=testpwd2 \
 -e BITNAMI_DEBUG=true \
  bitnami/openldap:2.5
```
 Then exec into the running container and created the `test.ldif` file with the following content:
```
$ cat test.ldif 
dn: olcDatabase={2}mdb,cn=config
changeType: modify
add: olcDbMaxSize
olcDbMaxSize: 2000000000
```
  and loaded it with:
```
$ ldapmodify -H "ldapi:///" -D "cn=config,cn=config" -wtestpwd2 -f test.ldif
```

**Comment by rafariossaa** [comment]
Hi,
  Did you have the chance to try what I indicated ?

**Comment by lebeier** [comment]
> Hi, Did you have the chance to try what I indicated ?

your solution returned 
```
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
```

**Comment by rafariossaa** [comment]
Hi @lebeier ,
  Not sure if  your issue is the same as this. There were several releases of the LDAP container since this issue was opened.
  Do you mind opening a new one and provide the versions, how you deployed it, etc ? That way we can provide a better support.
  Thanks forehand.
