### ISSUE TITLE
Container crashes without error

### ISSUE THREAD

**Issue by tebersefa** [bitnami/bitnami-docker-openldap#58]
Hi,

I am trying to use TLS with the latest version but container crashes without any error.

I run container with the following command:

`docker run --detach --name openldap   --network my-network --publish 1389:1389 --publish 1636:1636 --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword  -v ~/docker-openldap/certs:/opt/bitnami/openldap/certs -v ~/docker-openldap/data:/opt/bitnami/openldap/data  -e ALLOW_EMPTY_PASSWORD=yes -e LDAP_ENABLE_TLS=yes -e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/ldap.pem -e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/ldap-key.pem -e LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/rootCA.pem bitnami/openldap:latest`

And the logs are:

```
11:07:57.09 INFO  ==> ** Starting LDAP setup **
11:07:57.11 INFO  ==> Validating settings in LDAP_* env vars 
11:07:57.11 INFO  ==> Initializing OpenLDAP... 
11:07:57.12 INFO  ==> Creating LDAP online configuration 
11:07:57.13 INFO  ==> Starting OpenLDAP server in background 
11:07:57.14 INFO  ==> Configure LDAP credentials for admin user 
11:07:57.14 INFO  ==> Configuring TLS
```

Then container crashes and there is no more logs. 
What can be the reason of that? Is there any method to show more logs?

**Comment by pablogalegoc** [comment]
Hi @tebersef!

> Is there any method to show more logs?

There is, yes. You can set `BITNAMI_DEBUG` to true (see [logging](https://github.com/bitnami/bitnami-docker-openldap#logging)). Hope that helps!

**Comment by tebersefa** [comment]
Hi @pablogalegoc ,
It helped.
Thanks.
