### ISSUE TITLE
SSL cannot be enabled

### ISSUE THREAD

**Issue by ranguitamartin** [bitnami/bitnami-docker-openldap#59]
I have put all variables in docker-compose follow instructions
      **- LDAP_ENABLE_TLS=yes
      - LDAP_LDAPS_PORT_NUMBER=1636      
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/cert1.pem
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/privkey1.pem
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/fullchain1.pem**
But i cannor enable SSL mode.
When i execute step by step in container script
_/opt/bitnami/scripts/libopenldap.sh_
I can verify all my variables right 
And ldif generate follow steps.
_root@e5929c1777fa:/# ls -l ${LDAP_SHARE_DIR}/certs.ldif_
-rw-r--r-- 1 root root 331 Nov 19 12:34 /opt/bitnami/openldap/share/certs.ldif

This file has this contain

```
root@e5929c1777fa:/# cat  /opt/bitnami/openldap/share/certs.ldif
dn: cn=config
changetype: modify
replace: olcTLSCACertificateFile
olcTLSCACertificateFile: /opt/bitnami/openldap/certs/fullchain1.pem
-
replace: olcTLSCertificateFile
olcTLSCertificateFile: /opt/bitnami/openldap/certs/cert1.pem
-
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /opt/bitnami/openldap/certs/privkey1.pem
```

but when execute last method of this scripts i can see error

> root@e5929c1777fa:/# debug_execute ldapmodify -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/certs.ldif"
> SASL/EXTERNAL authentication started
> SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
> SASL SSF: 0
> modifying entry "cn=config"
> **ldap_modify: Insufficient access (50)**

¿Why i need pass to container for can modify and enable SSL?
Regards
Roberto

**Comment by javsalgar** [comment]
Could it be that the files you mounted don't have enough file permissions to be modified? 

I believe it is because of this

```
-rw-r--r-- 1 root root 331 Nov 19 12:34 /opt/bitnami/openldap/share/certs.ldif
```

The container is being run as non-root, therefore it would need group write access to be able to modify it. Are you mounting this ldif file?

**Comment by ranguitamartin** [comment]
I don't mount /opt/bitnami/openldap/share/certs.ldif, only i have executed step /opt/bitnami/scripts/libopenldap.sh for push contain here. This file i understand ins create when i start container because i have LDAP_ENABLE_TLS=yes

**Comment by javsalgar** [comment]
Could you let me know how you created the certificates in case they are self-signed? I would like to reproduce the issue.

**Comment by ranguitamartin** [comment]
I have generated wildcard certificate with let's encrypt, and i have used same certificates in other applications of subdomains and are right.

I have follow this instructions 
https://www.jesusamieiro.com/generar-un-certificado-ssl-wildcard-con-lets-encrypt/

**Comment by javsalgar** [comment]
Hi,

I recall this case, where I was unable to reproduce the issue. Could you try checking my comment there?

https://github.com/bitnami/bitnami-docker-openldap/issues/46#issuecomment-890861784

**Comment by ranguitamartin** [comment]
I have reproduce error follow your comment

I have generated new certificate and certificate CA following shell scripts from https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/
I launch LDAP with same of your parameter

docker run -it --rm --name openldap    \
-v /home/alerion/softdev/dev_tools/scripts/docker/ldap/certs:/opt/bitnami/openldap/certs \
-v /home/alerion/softdev/dev_tools/scripts/docker/ldap/myCA.crt:/opt/bitnami/openldap/myCA.crt \
--env LDAP_PORT_NUMBER=1389 -p 1389:1389 \
--env LDAP_LDAPS_PORT_NUMBER=1636 -p 1636:1636 \
--env LDAP_ADMIN_USERNAME=admin \
--env LDAP_ADMIN_PASSWORD=adminpassword \
--env LDAP_ROOT=dc=example,dc=com \
--env LDAP_USERS=user1 \
--env LDAP_PASSWORDS=newpass        \
-e LDAP_ENABLE_TLS=yes \
-e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/mydomain.crt  \
-e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/mydomain.key \
-e LDAP_TLS_CA_FILE=/opt/bitnami/openldap/myCA.crt \
-e BITNAMI_DEBUG=true \
-e LDAP_LOG_LEVEL=-1 \
 bitnami/openldap:latest


And i can see this error, same than with my original certificate.
```
 23:25:30.94 INFO  ==> ** Starting LDAP setup **
 23:25:30.97 INFO  ==> Validating settings in LDAP_* env vars
 23:25:30.99 INFO  ==> Initializing OpenLDAP...
 23:25:30.99 DEBUG ==> Ensuring expected directories/files exist...
 23:25:31.01 INFO  ==> Creating LDAP online configuration
Closing DB...
 23:25:31.03 INFO  ==> Starting OpenLDAP server in background
 23:25:31.05 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

 23:25:31.06 INFO  ==> Configuring TLS
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "cn=config"
ldap_modify: Other (e.g., implementation specific) error (80)
```


¿Exist some ldap log inside the container? ¿What version  OpenLDAP used in your comment?

**Comment by javsalgar** [comment]
Hi,

I tried again and was unable to reproduce the issue

```
 1 ❯ docker run --rm --name openldap     -v /tmp/certs:/opt/bitnami/openldap/certs --env LDAP_PORT_NUMBER=1389 -p 1389:1389 --env LDAP_LDAPS_PORT_NUMBER=1636 -p 1636:1636 --env LDAP_ADMIN_USERNAME=admin --env LDAP_ADMIN_PASSWORD=adminpassword --env LDAP_ROOT=dc=example,dc=com --env LDAP_USERS=user1 --env LDAP_PASSWORDS=newpass        -e LDAP_ENABLE_TLS=yes     -e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt     -e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key     -e LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/myCA.pem     bitnami/openldap:latest
Unable to find image 'bitnami/openldap:latest' locally
latest: Pulling from bitnami/openldap
ad3e435fd20e: Already exists
ac2a913f8b55: Pull complete
fce87f41f06b: Pull complete
7ab5ad4616d3: Pull complete
9ffb911f2cd9: Pull complete
037ab682ac98: Pull complete
315bad8c36d6: Pull complete
fc0e892e096c: Pull complete
Digest: sha256:91079847e8a0813e5f44385a696bcda2014b0688086e24b2fa395f9576a3b653
Status: Downloaded newer image for bitnami/openldap:latest
 10:16:35.33 INFO  ==> ** Starting LDAP setup **
 10:16:35.37 INFO  ==> Validating settings in LDAP_* env vars
 10:16:35.38 INFO  ==> Initializing OpenLDAP...
 10:16:35.40 INFO  ==> Creating LDAP online configuration
 10:16:35.43 INFO  ==> Starting OpenLDAP server in background
 10:16:35.45 INFO  ==> Configure LDAP credentials for admin user
 10:16:35.46 INFO  ==> Configuring TLS
 10:16:35.48 INFO  ==> Adding LDAP extra schemas
 10:16:35.51 INFO  ==> Creating LDAP default tree

 10:16:36.55 INFO  ==> ** LDAP setup finished! **
 10:16:36.58 INFO  ==> ** Starting slapd **
61a4a884.23097f68 0x7f7ae6af2080 @(#) $OpenLDAP: slapd 2.5.9 (Oct 26 2021 00:15:05) $
	@0959acab74d6:/bitnami/blacksmith-sandox/openldap-2.5.9/servers/slapd
61a4a884.23cce228 0x7f7ae6af2080 slapd starting
```

These are the exact steps I followed

```
openssl genrsa -des3 -out myCA.key 2048

openssl req -x509 -new -nodes -key myCA.key -sha256 -days 1825 -out myCA.pem

openssl genrsa -out openldap.key 2048

openssl req -new -key openldap.key -out openldap.csr

openssl x509 -req -in openldap.csr -CA myCA.pem -CAkey myCA.key -CAcreateserial -out openldap.crt -days 825 -sha256
```

I put bitnami as the Common Name and Organization.

**Comment by adamency** [comment]
@ranguitamartin Hi, sorry to bother you, in your last comment you said you fixed the issue and shared how you did it "like i explain in comment", but I don't see any comment of yours explaining the steps you did to fix it. In all of your past comments you are saying you have an error. Are you sure you posted the comment with your steps to fix the issue ? If so, where is it exactly (cause it is not in this issue) ? If not, would you mind sharing your steps ? Thanks a lot in advance
