### ISSUE TITLE
Issue with default docker-compose configuration

### ISSUE THREAD

**Issue by RazvanDev** [bitnami/bitnami-docker-openldap#60]
**Description**
Hello everone else having this problem running the the docker-compose file with the default configuration?
I have no previous experience with ldap, so I don't really know how to describe any possible cause
Container simply crashes

**Steps to reproduce the issue:**

1. just run docker-compose up with the default docker-compose file provided as an example

**Describe the results you received:**

```
 22:01:52.32 INFO  ==> ** Starting LDAP setup **
 22:01:52.35 INFO  ==> Validating settings in LDAP_* env vars
 22:01:53.59 INFO  ==> Initializing OpenLDAP...
 22:01:53.59 DEBUG ==> Ensuring expected directories/files exist...
 22:01:53.64 INFO  ==> Creating LDAP online configuration
**slapadd: could not add entry dn="cn=config" (line=1):**  <- this line strikes me as the possible culprit
```

**Describe the results you expected:**

The container just exits

**Comment by miguelaeh** [comment]
Hi @RazvanDev ,
It seems that there is already a config database, so it cannot be created again. Is it possible that you have some inconsistent data into your volume?

**Comment by RazvanDev** [comment]
> Hi @RazvanDev , It seems that there is already a config database, so it cannot be created again. Is it possible that you have some inconsistent data into your volume? Try to remove the volume and start it again

@miguelaeh Hello, I have used the default docker compose file from the repository. Did not add any extra ldif database. And the volume was empty. This is the docker compose file that I used:
https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.5/debian-10/docker-compose.yml

**Comment by miguelaeh** [comment]
Hi @RazvanDev ,
I am not able to reproduce the issue. 
Did you try to execute:
```
docker-compose down -v
```
and then
```
docker-compose up
```

**Comment by Slyke** [comment]
Figured it out. The `/bitnami/openldap` directory requires a chmod of 770, and not 660.
