### ISSUE TITLE
Passwords with comma or semi-colon not supported in `LDAP_PASSWORDS`

### ISSUE THREAD

**Issue by kriswuollett** [bitnami/bitnami-docker-openldap#61]
**Description**

From reading the source code, it appears to [not support passwords with the comma or semi-colon character](https://github.com/bitnami/bitnami-docker-openldap/blob/74462392828203877170e1622631645e1db05259/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L122) since `LDAP_PASSWORDS` is split using `tr ',;' ' '`. Any of those characters in the password would be converted to a space and the number of passwords would no longer match users.

**Possible Solution**

Add a variable like `LDAP_PASSWORDS_BASE64` which defaults to `false` for backwards compatibility. From what I can tell the standard [base64 table](https://en.wikipedia.org/wiki/Base64#Base64_table) does not include a comma or semi-colon, so a list of base64-encoded passwords could be separated using the current method.

**Comment by kriswuollett** [comment]
Or perhaps one should be specifying them in a an encoded format like `{SSHA}` as described in the [OpenLDAP FAQ](https://www.openldap.org/faq/data/cache/347.html)? May just be an easy solution to document that complex password should use an encoded password scheme. I assume those will just pass through ok?

**Comment by carrodher** [comment]
Thanks for creating the issue. Would you like to create a PR adding the solution you have in mind? The team will be happy to review it and provide feedback
