### ISSUE TITLE
Add support for reading passwords from secrets

### ISSUE THREAD

**Issue by kriswuollett** [bitnami/bitnami-docker-openldap#62]
**Description**

It isn't very convenient to create a concatenated list of initial passwords for `LDAP_USERS`. In a container environment, it may likely that users of the container will want to supply passwords from cluster secrets. Supporting this may be able to deprecate the #61 issue if the current `LDAP_PASSWORDS` goes away.

**Possible Solutions**

1. For each user in `LDAP_USERS` first try fetching the individual password by reading the file specified by `LDAP_PASSWORD_${user}_FILE` if it exists, otherwise fetch the individual password from environment variable `LDAP_PASSWORD_${user}`. There is precedence for this pattern in Docker, see [Docker Secrets for postgres](https://github.com/docker-library/docs/blob/master/postgres/README.md#docker-secrets). This pattern could be used by users who which to use env from secret references in Kubernetes, or individual mounted secret files.
2.  For each user in `LDAP_USERS` the password could be found by looking in the directory specified by a new variable `LDAP_PASSWORDS_PATH` in the file with the same name as the user. This pattern could be used by users who wish to create a single Kubernetes secret that is mounted as a volume with a key/value for each user. For example, to find the password for `user01`, a Kubernetes secret would be mounted at `/var/secrets/user-passwords` in which there would be a file `user01` with the contents being the password.

**Comment by kriswuollett** [comment]
**Possible Solutions (addition)**

3. Apply the pattern specified in suggestion 1 written above looking for the file named by `*_PASSWORD_FILE` variable before checking for `*_PASSWORD` for `LDAP_ADMIN` and `LDAP_CONFIG_ADMIN`.

**Comment by carrodher** [comment]
Thanks for creating the issue. This approach is supported in other containers but not implemented in OpenLDAP. For instance MariaDB:
```
MARIADB_ROOT_PASSWORD_FILE: Path to a file that contains the admin user password. This will override the value specified in MARIADB_ROOT_PASSWORD. No defaults.
```
https://github.com/bitnami/bitnami-docker-mariadb#setting-the-root-password-on-first-run

Would you like to create a PR to solve this issue? The team will be happy to review it and provide feedback

**Comment by kriswuollett** [comment]
@carrodher I've put together a draft change request in #65 which I created an untested minimal change style patch. In general I'd prefer more `info`-level logging during the initialization process, but the current `libopenldap.sh` script only seems to mostly print `error`-level logging. The patch-style also does not seem optimal if the libraries to support #63 become available in the base image.

**Comment by juan131** [comment]
Hi @kriswuollett 

Thanks so much for your PR! Please check my review comments when you have a chance.
