### ISSUE TITLE
Add support for more recent password schemes like `PBKDF2-SHA256`

### ISSUE THREAD

**Issue by kriswuollett** [bitnami/bitnami-docker-openldap#63]
**Description**

I wish to be able to use as well as migrate password entries between different systems with a more robust password scheme. I see that the libraries needed to load schemes like `PBKDF2-SHA256` are available in [buster](https://packages.debian.org/buster/amd64/slapd-contrib/filelist) which should be easily loaded in the [server config](http://manpages.ubuntu.com/manpages/impish/man5/slapo-pw-pbkdf2.5.html). I got a shell in a running instance and I was unable to find those contrib libraries.

I tried seeing if I could just rebuild this image myself, but I discovered that the bitnami `openldap` package is pulled down in the [`Dockerfile`](https://github.com/bitnami/bitnami-docker-openldap/blob/e79fd737c296030241f7190b2785c7cafca999ea/2.5/debian-10/Dockerfile#L12) from https://downloads.bitnami.com/files/stacksmith/openldap-2.5.9-0-linux-amd64-debian-10.tar.gz. Specifically [here in `libcomponent.sh`](https://github.com/bitnami/bitnami-docker-openldap/blob/e79fd737c296030241f7190b2785c7cafca999ea/2.5/debian-10/prebuildfs/opt/bitnami/scripts/libcomponent.sh#L57). In the root of that package there is a `COPYING` file that says it is GPL v2, and a `bitnami.json` file with contents:

```
{
    "id": "com.bitnami.openldap",
    "name": "openldap",
    "revision": "0",
    "author":     {
        "name": "Bitnami",
        "url": "https://bitnami.com"
    },
    "version": "2.5.9"
}
```

I couldn't find a GitHub repository with the source code for that bitnami OpenLDAP distribution. Where can I find it if I wanted to try compiling/including the contrib part of it myself?

**Comment by Mauraza** [comment]
Hi @kriswuollett,

is not a website with this tarball but they are publicly available. If you uncompress them you will see that is only the OpenLDAP official files plus some metadata.

**Comment by kriswuollett** [comment]
@Mauraza, understood, thanks!

**Comment by kriswuollett** [comment]
If you're considering adding this feature, you'll find that the unpatched OpenLDAP distribution has PBKDF2 rounds [fixed at 10000 iterations](https://github.com/openldap/openldap/blob/fbd4f9abdd33b8c443a00fc23c1ad44148975d5c/contrib/slapd-modules/passwd/pbkdf2/pw-pbkdf2.c#L39) which is an issue when generating hashes for accounts if it needs to be configurable. I haven't found an easier way of generating hashes with a larger iteration count than using [passlib.hash](https://passlib.readthedocs.io/en/stable/lib/passlib.hash.pbkdf2_digest.html) with python when running in a container. If you are building from source, then you could patch it like [this version](https://github.com/hamano/openldap-pbkdf2/blob/1faca5029ed68304a5148731fad3b7e76216e51e/pw-pbkdf2.c#L682).

**Comment by juan131** [comment]
Hi @kriswuollett 

We don't have a policy to patch the upstream source when compiling unless it's strictly required for security reasons (e.g. the upstream code is affected by a critical CVE and there are no new releases patching it). Otherwise, we wait for the upstream project to include any required improvement.

By the way, we currently download the OpenLDP upstream tarballs from the link below:

- https://mirror.koddos.net/OpenLDAP/openldap-release/

**Comment by kriswuollett** [comment]
@juan131, ok, so sounds like anything contrib like [contrib/slapd-modules/passwd/pbkdf2](https://git.openldap.org/openldap/openldap/-/tree/master/contrib/slapd-modules/passwd/pbkdf2), even if bundled with the original source, would need to be compiled and added as a layer to this container image on one's own? If so, no worries if you need to close this issue, as it looks like I may have to build & maintain my own container image for it.

**Comment by Mauraza** [comment]
Hi @kriswuollett,

> even if bundled with the original source, would need to be compiled and added as a layer to this container image on one's own?

That's right. Closing this out now, do not hesitate to write us back if you have any other questions.
