### ISSUE TITLE
[Question] How can I acquire ldap logs?

### ISSUE THREAD

**Issue by italiks** [bitnami/bitnami-docker-openldap#66]
Hello, could you please help me to find out how can I get service logs?

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami OpenLDAP container image but about how the application is being used.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by ruckc** [comment]
according to the container README, turning on BITNAMI_DEBUG=true does it, but it doesn't.

**Comment by carrodher** [comment]
`BITNAMI_DEBUG` increase the verbosity of the initialization logic traces, but the service logs appear by default after `openldap_1  |  16:50:15.50 INFO  ==> ** Starting LDAP setup **
openldap_1  |  16:50:15.56 INFO  ==> Validating settings in LDAP_* env vars
openldap_1  |  16:50:15.59 INFO  ==> Initializing OpenLDAP...
openldap_1  |  16:50:15.61 INFO  ==> Creating LDAP online configuration
openldap_1  |  16:50:15.63 INFO  ==> Starting OpenLDAP server in background
openldap_1  |  16:50:15.65 INFO  ==> Configure LDAP credentials for admin user
openldap_1  |  16:50:15.66 INFO  ==> Adding LDAP extra schemas
openldap_1  |  16:50:15.68 INFO  ==> Creating LDAP default tree
openldap_1  |  16:50:16.74 INFO  ==> ** LDAP setup finished! **
openldap_1  |
openldap_1  |  16:50:16.77 INFO  ==> ** Starting slapd **
openldap_1  | 61d86f48.2e815644 0x7f9a2162c000 @(#) $OpenLDAP: slapd 2.5.9 (Jan  3 2022 07:46:52) $
openldap_1  | 	@3d710d17bc08:/bitnami/blacksmith-sandox/openldap-2.5.9/servers/slapd
openldap_1  | 61d86f48.2f08a892 0x7f9a2162c000 slapd starting`:
```
openldap_1  |  16:50:15.50 INFO  ==> ** Starting LDAP setup **
openldap_1  |  16:50:15.56 INFO  ==> Validating settings in LDAP_* env vars
openldap_1  |  16:50:15.59 INFO  ==> Initializing OpenLDAP...
openldap_1  |  16:50:15.61 INFO  ==> Creating LDAP online configuration
openldap_1  |  16:50:15.63 INFO  ==> Starting OpenLDAP server in background
openldap_1  |  16:50:15.65 INFO  ==> Configure LDAP credentials for admin user
openldap_1  |  16:50:15.66 INFO  ==> Adding LDAP extra schemas
openldap_1  |  16:50:15.68 INFO  ==> Creating LDAP default tree
openldap_1  |  16:50:16.74 INFO  ==> ** LDAP setup finished! **
openldap_1  |
openldap_1  |  16:50:16.77 openldap_1  |  16:50:15.50 INFO  ==> ** Starting LDAP setup **
openldap_1  |  16:50:15.56 INFO  ==> Validating settings in LDAP_* env vars
openldap_1  |  16:50:15.59 INFO  ==> Initializing OpenLDAP...
openldap_1  |  16:50:15.61 INFO  ==> Creating LDAP online configuration
openldap_1  |  16:50:15.63 INFO  ==> Starting OpenLDAP server in background
openldap_1  |  16:50:15.65 INFO  ==> Configure LDAP credentials for admin user
openldap_1  |  16:50:15.66 INFO  ==> Adding LDAP extra schemas
openldap_1  |  16:50:15.68 INFO  ==> Creating LDAP default tree
openldap_1  |  16:50:16.74 INFO  ==> ** LDAP setup finished! **
openldap_1  |
openldap_1  |  16:50:16.77 INFO  ==> ** Starting slapd **
openldap_1  | 61d86f48.2e815644 0x7f9a2162c000 @(#) $OpenLDAP: slapd 2.5.9 (Jan  3 2022 07:46:52) $
openldap_1  | 	@3d710d17bc08:/bitnami/blacksmith-sandox/openldap-2.5.9/servers/slapd
openldap_1  | 61d86f48.2f08a892 0x7f9a2162c000 slapd starting
openldap_1  | 61d86f48.2e815644 0x7f9a2162c000 @(#) $OpenLDAP: slapd 2.5.9 (Jan  3 2022 07:46:52) $
openldap_1  | 	@3d710d17bc08:/bitnami/blacksmith-sandox/openldap-2.5.9/servers/slapd
openldap_1  | 61d86f48.2f08a892 0x7f9a2162c000 slapd starting
```

**Comment by ruckc** [comment]
it would be nice if we could pass command line arguments to slapd such as `-d 1` to get its debug logs for a crashing container

**Comment by migruiz4** [comment]
Hi @ruckc,

Any additional argument you pass to the container command along with `/opt/bitnami/scripts/openldap/run.sh`, will be added to the execution of the `slapd` binary:

 https://github.com/bitnami/bitnami-docker-openldap/blob/a59b7cee0170b5a42ae08214133630a867ae213b/2.6/debian-10/rootfs/opt/bitnami/scripts/openldap/run.sh#L27-L32

To add the command line argument `-d 1`, run the container with the command `/opt/bitnami/scripts/openldap/run.sh -d 1`

**Comment by ruckc** [comment]
If you specify those then the LDAP initialization doesn't happen.

**Comment by migruiz4** [comment]
Sorry for the late response @ruckc,

Indeed there is an issue with the entrypoint where `setup.sh` would be skipped if extra arguments are provided.

A new release of the `bitnami/openldap` will be released soon fixing it.

**Comment by jeacott1** [comment]
related, how can I turn on the ACL logs for this container? BITNAMI_DEBUG=true doesnt seem to do it.

**Comment by migruiz4** [comment]
Hi @ruckc,

I would like to let you know that a new version of the openldap image has been released fixing this issue.

To enable logs, overwrite the container command with:
```
version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    command: ['/opt/bitnami/scripts/openldap/run.sh', '-d', '1']
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local
```

@jeacott1 enabling ACL logs should work the same way, but overwrite the container command wih `command: ['/opt/bitnami/scripts/openldap/run.sh', '-d', '128']` instead.

Logging codes can be obtained from this document: https://www.openldap.org/doc/admin24/slapdconfig.html

Make sure to use versions `2.6.0-debian-10-r13`, `2.4.59-debian-10-r183`, `2.5.9-debian-10-r82` (or above when released)

**Comment by jeacott1** [comment]
@migruiz4 thank you!
although the ```command: ['/opt/bitnami/scripts/openldap/run.sh', '-d', '128']``` confused me for a moment.
I'm deploying in k8s, and this is actually just ```args: ["/opt/bitnami/scripts/openldap/run.sh", "-d", "128"]``` (for anyone else who comes across this).

**Comment by migruiz4** [comment]
Great! Thank you for your feedback @jeacott1, I'm happy that my comment was helpful.

Yes, in Kubernetes `command` would be equivalent to overriding the container entrypoint (using docker-compose field `entrypoint`, for example) while docker-compose `command` field is equivalent to Kubernetes `arg` spec.

I will now close this issue, if you have any further issues please let me know.

**Comment by jeacott1** [comment]
@migruiz4 just to be clear, there is no need to override entrypoint in k8s at all. 
literally just adding something like this is enough

```
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:2.6
          args: ["/opt/bitnami/scripts/openldap/run.sh", "-d", "128"]
```
