### ISSUE TITLE
Bootstrap LDAP database from LDIF file

### ISSUE THREAD

**Issue by Bengrunt** [bitnami/bitnami-docker-openldap#7]
**Description**

I'd like to bootstrap my LDAP server from a LDIF file.

**Describe the results you expected:**

Adding a way through the `entrypoint.sh` or `run.sh` scripts to run a ldapadd of a LDIF file (most likely bind mounted in the container) would be great. That way my LDAP is already populated.

**Comment by javsalgar** [comment]
Hi,

According to https://github.com/bitnami/bitnami-docker-openldap/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/openldap/run.sh, you can specify extra args to the container command, so you could mount the ldif file in whatever location you prefer and add the flags to use that ldif file.

**Comment by Bengrunt** [comment]
Hi, thanks for the answer.

However, I'm no bash nor LDAP expert but I don't know of any slapd flag that would allow me to load a LDIF file.
The man page does not mention any such thing.

There's only the notion of using slapd in "tool" mode to run actions such as with ldapadd but then I wouldn't be able to start the daemon as well, right?

Thanks for the help.

**Comment by javsalgar** [comment]
Hi,

Looking at it, you are right, it would be one thing or the other. Could you detail the exact commands you would require to have your environment set up? This way we could implement that functionality in the container.

**Comment by Bengrunt** [comment]
Hi, thanks for taking some time on this.

I did a few tweaks on the `libopenldap.sh` file in order to add the possibility of bootstrapping with a LDAP file and I managed to get what I wanted.

I will to prepare a PR as soon as I get a few minutes.
Once again, I'm no expert so it might not be exactly as good as you'd like it to be but I guess we could review it together and start from there if you wish.

**Comment by christian-scheible** [comment]
Hi,

I think something like the function in this docker image would be great:
https://github.com/osixia/docker-openldap#seed-ldap-database-with-ldif.

In this image it is possible to mount LDIF files and the LDAP bootstrapped with the given files.

**Comment by juan131** [comment]
Thanks so much for your contribution @Bengrunt ! I added some comments, please review them when you have a chance.

**Comment by Bengrunt** [comment]
Thanks for the review @juan131 

I'll to get on this tomorrow.

**Comment by wiibaker** [comment]
I've tried this and seems to work, though, there is issue with the order the files are processed. I dropped a comment

https://github.com/bitnami/bitnami-docker-openldap/pull/8/files#r521347639

Also we have issue that we need custom schema elements loaded _before_ the LDIF data files are loaded and I created a new issue #14 about it.

**Comment by saadlu** [comment]
the current version of the code does not work as expected with `BITNAMI_DEBUG`.

I have made a comment on this:

https://github.com/bitnami/bitnami-docker-openldap/pull/8/files#r537401900

**Comment by juan131** [comment]
Thanks @saadlu ! I just responded you in the PR
