### ISSUE TITLE
LDAP accessible without any authentication

### ISSUE THREAD

**Issue by louisgls** [bitnami/bitnami-docker-openldap#70]
**Description**

The LDAP server is accessible without specifying any authentication

**Steps to reproduce the issue:**

1. run the image with : 
```
docker run -p 1389:1389 --detach --rm --name openldap \
  --network my-network \
  --env LDAP_ADMIN_USERNAME=admin \
  --env LDAP_ADMIN_PASSWORD=adminpassword \
  --env LDAP_USERS=customuser \
  --env LDAP_PASSWORDS=custompassword \
  bitnami/openldap:latest
```
2. Use a ldap client to log in, do not specify any authentication method.
You can also use python-ldap : 
```
import sys,ldap
with open("test.ldif","w") as fo:
    l = ldap.initialize('ldap://localhost:1389')    
    s = ldap.asyncsearch.LDIFWriter(l,fo)
    s.startSearch("dc=example,dc=org",  ldap.SCOPE_SUBTREE, None)
    s.processResults()
```

**Describe the results you received:**

The content of the server is accessible.

**Describe the results you expected:**

The content of the server should not be accessible.

**Additional information**

I also tried to set LDAP_ALLOW_ANON_BINDING which correctly blocks when an anonymous bind is attempted, but we can still search through the whole directory as long as we don't try to bind to the ldap.

**Comment by juan131** [comment]
Hi @louisgls 

The current env. variables allow you to configure easily authentication, but they don't allow you to configure authorization in a similar way. To have authorization, you need to configure Access Control in the server, see:

- https://www.openldap.org/doc/admin24/access-control.html
