### ISSUE TITLE
Insufficient access in loading custom LDIF

### ISSUE THREAD

**Issue by devent** [bitnami/bitnami-docker-openldap#71]
**Description**

Try to add the custom LDIF.

```
dn: cn=module{0},cn=config
changetype: add
objectClass: olcModuleList
cn: module{0}
olcModuleLoad: memberof
```

Error is

```
ldap_add: Insufficient access (50)
```
I see that the LDIFs are added with the admin account but I need the config admin.

https://github.com/bitnami/bitnami-docker-openldap/blob/2.6.0-debian-10-r6/2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L418

`ldapadd -f {} -H 'ldapi:///' -D \"$LDAP_ADMIN_DN\" -w \"$LDAP_ADMIN_PASSWORD\""
}`

Why it's not using the config admin? Or just `-Y EXTERNAL`

**Comment by devent** [comment]
I need to use `ldapadd -f {} -Y EXTERNAL -H "ldapi:///"` because otherwise I can't add users in custom LDIFs.

**Comment by javsalgar** [comment]
Hi,

Could you share the exact command in order to reproduce the issue?

**Comment by Moep90** [comment]
https://github.com/bitnami/bitnami-docker-openldap/blob/2.6.0-debian-10-r6/2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L418 should look like:
```
 find "$LDAP_CUSTOM_LDIF_DIR" -maxdepth 1 \( -type f -o -type l \) -iname '*.ldif' -print0 | sort -z | xargs --null -I{} bash -c ". /opt/bitnami/scripts/libos.sh && debug_execute ldapadd -f {} -Y EXTERNAL -H 'ldapi:///' -D \"$LDAP_ADMIN_DN\" -w \"$LDAP_ADMIN_PASSWORD\""
```

**Comment by devent** [comment]
I created my own fork that uses the config admin.

**Comment by fmulero** [comment]
Thanks a lot @devent  for raising this issue, I'll take a glance to your PR

As @Moep90 pointed out, adding the `ldif` file to `/opt/bitnami/openldap/etc/schema/` is a workaround for this issue.

**Comment by dunatotatos** [comment]
I just encountered this exact issue (Insufficient access when trying to edit cn=config). I believe this issue should be re-open, as none of the associated PR was merged.

**Comment by fmulero** [comment]
Hi @dunatotatos,

Are you facing the same problem described here? Doesn't the [workoround suggested](https://github.com/bitnami/bitnami-docker-openldap/issues/71#issuecomment-1026443653) solve your issue?
