### ISSUE TITLE
[Question] When will the `latest` tag will be moved from `2.5` to `2.6`?

### ISSUE THREAD

**Issue by Houlistonm** [bitnami/bitnami-docker-openldap#72]
**Description**

When will the `latest` tag will be moved from `2.5` to `2.6`?
If this is documented somewhere, please point me at the docs.

```
TAG latest
DIGEST 3c240a8859ac

TAG 2.5.11-debian-10-r0
DIGEST 3c240a8859ac

TAG 2.5.11
DIGEST 3c240a8859ac
```

**Comment by carrodher** [comment]
Thanks for letting us know, we just changed the release pipeline and the next OpenLDAP 2.6 should make the `latest` tag point to the different rolling tags for 2.6.X

**Comment by Houlistonm** [comment]
@carrodher Thank you for the update, please dispense with this issue as you see fit.

**Comment by carrodher** [comment]
The latest release of a new revision for the 2.6 branch changed the `latest` tag (and other defaults) to use this branch as the latest stable at this moment, see https://github.com/bitnami/bitnami-docker-openldap/commit/1cdf6f9d43ca23a2eaa53a1252aa64462919e055
