### ISSUE TITLE
java schema being specified with `-e LDAP_EXTRA_SCHEMAS=java`

### ISSUE THREAD

**Issue by geckotechcr** [bitnami/bitnami-docker-openldap#74]
**Description**

The image runs fine with defaults using podman on OL8.  However if i add the following switch to the podman invokation of the container `-e LDAP_EXTRA_SCHEMAS=java` the container fails and hangs on the following:

 21:57:18.98 INFO  ==> ** Starting LDAP setup **
 21:57:19.01 INFO  ==> Validating settings in LDAP_* env vars
 21:57:19.02 INFO  ==> Initializing OpenLDAP...
 21:57:19.03 INFO  ==> Creating LDAP online configuration
 21:57:19.05 INFO  ==> Starting OpenLDAP server in background
 21:57:19.06 INFO  ==> Configure LDAP credentials for admin user
 21:57:19.07 INFO  ==> Adding LDAP extra schemas

**Steps to reproduce the issue:**

1. launching the container as follows works fine:
`#podman run --name openldap -d -p 1389:1389 -p 1636:1636 bitnami/openldap:latest`
2. launching froms same image with aforementioned switch fails:
`# podman run --name openldap -d -p 1389:1389 -p 1636:1636 -e LDAP_EXTRA_SCHEMAS=java bitnami/openldap:latest`

The java.ldif and java.schema are located in the /opt/bitnami/openldap/etc/schema directory of container.  And I assume the pathing to those schemas is already known.  

**Describe the results you received:**

Container exits whith the following line posted to the log:

` 21:57:19.07 INFO  ==> Adding LDAP extra schemas`

**Describe the results you expected:**

I had hoped it would launch/run as it does without this switch but regrettably it did not.

Thanks

**Comment by geckotechcr** [comment]
I do not understand the format of LDIF, but the java.ldif file (organic to the image) seems as it might have been cut/paste from windows host or something that did wordwrap.  Point being there appear to be unnecessary cr/lf..   (as compared to other ldifs in the same path)

**Comment by javsalgar** [comment]
Hi,

Could you try again with the variable `BITNAMI_DEBUG=true`? this may provide more debugging output.

**Comment by geckotechcr** [comment]
Javier, thanks for reply:  I was wrong, in that it does not seem to  be hanging on the importation of Java Schema, but rather the next step creating the LDAP default tree.
```

 13:49:06.37 INFO  ==> ** Starting LDAP setup **
 13:49:06.40 INFO  ==> Validating settings in LDAP_* env vars
 13:49:06.41 INFO  ==> Initializing OpenLDAP...
 13:49:06.41 DEBUG ==> Ensuring expected directories/files exist...
 13:49:06.42 INFO  ==> Creating LDAP online configuration
 13:49:06.44 INFO  ==> Starting OpenLDAP server in background
 13:49:06.45 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

 13:49:06.46 INFO  ==> Adding LDAP extra schemas
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=java,cn=schema,cn=config"

 13:49:06.47 INFO  ==> Creating LDAP default tree
ldap_add: Invalid syntax (21)
        additional info: objectClass: value #0 invalid per syntax
adding new entry "dc=example,dc=org"

adding new entry "ou=users,dc=example,dc=org"

adding new entry "cn=user01,ou=users,dc=example,dc=org"
```

Not sure what the conflict might be...

**Comment by geckotechcr** [comment]
Miguel, Thanks for the clarification.  I had simply assumed that the defaults would still apply and that I was merely adding to the default list.  I should have tried that before wasting your time, but it didn't even occur to me.
Thanks again for your support.

**Comment by migruiz4** [comment]
You are welcome @geckotechcr! I'm glad that my answer helped you solve the issue.
