### ISSUE TITLE
There is no slapd-contrib

### ISSUE THREAD

**Issue by Shihta** [bitnami/bitnami-docker-openldap#79]
### Name and Version

2.6.1

### What steps will reproduce the bug?

`slappasswd -o module-load=pw-argon2 -h {ARGON2}  -s abcdefg`

### What is the expected behavior?

there should be a method to install pw-argon2

### What do you see instead?

`lt_dlopenext failed: (pw-argon2) file not found`

**Comment by binaryape** [comment]
The password hashing methods included at the moment are all awful, so it would be of huge benefit for the some of the modern methods such as bcrypt or argon2 to be included by default. I don't think adding the slapd-contrib package will work, the modern hash modules would need to be compiled.

**Comment by alemorcuq** [comment]
Thanks @binaryape. I'll create an internal task to support those methods.

**Comment by binaryape** [comment]
@alemorcuq Thanks! It might be simpler to manage with v2.6 of OpenLDAP: with 2.4 3rd-party modules were needed to add better hashing, but the Argon2 password hashing module is now included as an option in the 2.6 source code. If the OS has the libsodium or libargon2 libraries present, there are some compile-time switches to enable Argon2.

**Comment by alemorcuq** [comment]
2.4 will be deprecated soon on our side 👍

**Comment by binaryape** [comment]
This is how I'm working around it at the moment as a quick fix (this might not be the best way)

```Dockerfile
FROM bitnami/openldap:2.6.1 AS pw_build

USER root

RUN install_packages build-essential git groff groff-base libargon2-dev libltdl-dev unixodbc-dev pkg-config libsasl2-dev openssl
WORKDIR /build
RUN git clone -b OPENLDAP_REL_ENG_2_6 https://git.openldap.org/openldap/openldap.git
RUN cd /build/openldap && ./configure --with-argon2=libargon2 --enable-modules --enable-argon2=yes --enable-passwd && make depend && make && make install

FROM bitnami/openldap:2.6.1

USER root
RUN install_packages libargon2-1
USER 1001

COPY --from=pw_build --chown=1001 /usr/local/libexec/openldap/ /opt/bitnami/openldap/lib/openldap/

# Etc

```

This only provides Argon2, not Bcrypt or PBKDF2

**Comment by alemorcuq** [comment]
Thanks, that's very useful.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
