### ISSUE TITLE
LDAP_CUSTOM_LDIF_DIR apparently not working: No entry in the logs, apparently no database created.

### ISSUE THREAD

**Issue by johanneskastl** [bitnami/bitnami-docker-openldap#82]
### Name and Version

bitnami/openldap:2.5.11

### What steps will reproduce the bug?

1. I set this up in Kubernetes running with the environment variable `LDAP_CUSTOM_LDIF_DIR` set:
```
$ kubectl exec -it pod/openldap-bitnami-6b45db8c5-9sxs7 -- env|grep LDIF
LDAP_CUSTOM_LDIF_DIR=/ldif_import/
$
```

2. I put a file into that directory, mounted from a Kubernetes secret.
3. I find no trace in the server's logs (even with BITNAMI_DEBUG set to true) that this directory is being checked.

I can `ldapsearch` the cn=config using my LDAP_CONFIG_ADMIN_USERNAME user and password. But I can not connect as the configured LDAP_ADMIN_USERNAME.

Or rather: I can connect as LDAP_ADMIN_USERNAME, but only using the default suffix of `dc=example,dc=org`.

It seems like it is just ignored.

Did I miss any steps?

### What is the expected behavior?

I should get a message that the file(s) was/were imported, or an error if something could not be imported.

### What do you see instead?

No errors, no import happened apparently.

**Comment by johanneskastl** [comment]
This line checks if the directory is empty:
https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L474

It should detect that there is something in there, the same `is_dir_empty` detected files in the other mount.

Could it be that this `is_dir_empty` routine does NOT detect links in that directory and hence thinks the directory is empty?

Kubernetes secrets are mounted in a special way and the file is actually shown as a link:
```
$ kubectl exec -it pod/openldap-bitnami-65fffb578c-g4wqc -- ls -l /ldif_import/
lrwxrwxrwx. 1 root 1001 18 Mar 21 20:10 import.ldif -> ..data/import.ldif

```

**Comment by javsalgar** [comment]
Could you try entering the container, source the `/opt/bitnami/scripts/libopenldap.sh` file and executing the `is_dir_empty` function? What does it return?

**Comment by johanneskastl** [comment]
> /opt/bitnami/scripts/libopenldap.sh

```
I have no name!@openldap-bitnami-6b45db8c5-t9hmp:/$ source /opt/bitnami/scripts/libopenldap.sh
I have no name!@openldap-bitnami-6b45db8c5-t9hmp:/$ ls -lh /ldif_import/
total 0
lrwxrwxrwx. 1 root 1001 18 Mar 22 09:28 import.ldif -> ..data/import.ldif
I have no name!@openldap-bitnami-6b45db8c5-t9hmp:/$ is_dir_empty /ldif_import/
I have no name!@openldap-bitnami-6b45db8c5-t9hmp:/$ echo $?
1
I have no name!@openldap-bitnami-6b45db8c5-t9hmp:/$
```

I think that might actually be the problem, it returns an exit code of 1.

**Comment by carrodher** [comment]
In that case, according to the logic
```bash
            if ! is_dir_empty "$LDAP_CUSTOM_LDIF_DIR"; then
                ldap_add_custom_ldifs
            else
                ldap_create_tree
            fi
```
it is going to the if statement and executing the `ldap_add_custom_ldifs`:
```bash
ldap_add_custom_ldifs() {
    info "Loading custom LDIF files..."
    warn "Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables..."
    find "$LDAP_CUSTOM_LDIF_DIR" -maxdepth 1 \( -type f -o -type l \) -iname '*.ldif' -print0 | sort -z | xargs --null -I{} bash -c ". /opt/bitnami/scripts/libos.sh && debug_execute ldapadd -f {} -H 'ldapi:///' -D \"$LDAP_ADMIN_DN\" -w \"$LDAP_ADMIN_PASSWORD\""
}
```

**Comment by johanneskastl** [comment]
@carrodher You are right, I got the logic wrong. Stupid negations... :-)

But I do not see any of those info or warn message in the logs.

```
 07:53:26.65 INFO  ==> ** Starting LDAP setup **
 07:53:26.67 INFO  ==> Validating settings in LDAP_* env vars
 07:53:26.67 INFO  ==> Initializing OpenLDAP...
 07:53:26.68 DEBUG ==> Ensuring expected directories/files exist...
 07:53:26.68 INFO  ==> Creating LDAP online configuration
 07:53:26.70 INFO  ==> Starting OpenLDAP server in background
 07:53:26.71 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

modifying entry "olcDatabase={0}config,cn=config"

modifying entry "olcDatabase={0}config,cn=config"

 07:53:26.72 INFO  ==> Configuring TLS
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "cn=config"

 07:53:26.73 INFO  ==> Skipping default schemas/tree structure
 07:53:27.74 INFO  ==> ** LDAP setup finished! **

 07:53:27.77 INFO  ==> ** Starting slapd **
623c2377.2e8cebce 0x7f7a3f9c5000 @(#) $OpenLDAP: slapd 2.5.11 (Mar  1 2022 15:23:23) $
        @bc169e08a584:/bitnami/blacksmith-sandox/openldap-2.5.11/servers/slapd
623c2377.2ed9d924 0x7f7a3f9c5000 slapd starting
623c237f.1a96aae9 0x7f7a3e225700 conn=1000 fd=14 ACCEPT from IP=10.0.0.19:46848 (IP=0.0.0.0:1389)
623c237f.1a9a4898 0x7f7a3da24700 conn=1000 fd=14 closed (connection lost)
```

**Comment by johanneskastl** [comment]
I actually found the issue.

https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L466

The whole logic to do something, whether create schemas or the "default tree" or import LDIF files, is include in the if-condition for `LDAP_SKIP_DEFAULT_TREE`.

I thought that is only for creation of the default tree specified by the variables, but actually it also prohibits the import of the LDIF files.

I think this is a bug or a bug in the documentation:

```
LDAP_SKIP_DEFAULT_TREE: Whether to skip creating the default LDAP tree based on LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP. Default: no
```

To me this sounds like it should only affect the "default LDAP tree".

**What do you think? PR for the documentation?

Or would it be better to change the script behaviour, i.e. really only skip the default tree generation, but not creation/addition of schemas or importing of LDIF files or custom schemas=**

**Comment by johanneskastl** [comment]
Closing this and proceeding in #86, as this might be misleading and hard to understand, what the actual problem is...
