### ISSUE TITLE
Split generation of default tree from setting up schemas (and extra schemas) and importing of LDIF files

### ISSUE THREAD

**Issue by johanneskastl** [bitnami/bitnami-docker-openldap#86]
### Name and Version

bitnami/openldap:2.5.11

### What steps will reproduce the bug?

Setting the variable `LDAP_SKIP_DEFAULT_TREE` will skip creation of the "content" of the LDAP tree, like users and such.

But it will also skip adding schemas to the configuration, as well as importing LDIF files:
https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L466
```
        if is_boolean_yes "$LDAP_SKIP_DEFAULT_TREE"; then
            info "Skipping default schemas/tree structure"
        else
            # Initialize OpenLDAP with schemas/tree structure
            ldap_add_schemas
            if [[ -f "$LDAP_CUSTOM_SCHEMA_FILE" ]]; then
                ldap_add_custom_schema
            fi
```

From what I understood in #83 the automatic import cannot modify things under `cn=config`, so adding the schemas to the `LDAP_CUSTOM_LDIF_DIR` directory will not work.

I think the logic should be:
```
        # Initialize OpenLDAP with schemas/tree structure
        ldap_add_schemas
        if [[ -f "$LDAP_CUSTOM_SCHEMA_FILE" ]]; then
            ldap_add_custom_schema
        fi
        if is_boolean_yes "$LDAP_SKIP_DEFAULT_TREE"; then
            info "Skipping default schemas/tree structure"
        else
                ldap_create_tree
        fi
        if ! is_dir_empty "$LDAP_CUSTOM_LDIF_DIR"; then
            ldap_add_custom_ldifs
        fi
```

### What is the expected behavior?

From the documentation:
```
LDAP_SKIP_DEFAULT_TREE: Whether to skip creating the default LDAP tree based on LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP. Default: no
```
I would argue that this should **ONLY** skip the actual creation of the default tree. And nothing else. So it **should** create/add schemas and import LDIF objects.

(As all of the mentioned variables like `LDAP_USERS` have default values, it makes sense to only skip creation of LDAP entries from those variables. But still have schemas and import LDIFs...)

### What do you see instead?

Setting `LDAP_CUSTOM_SCHEMA_FILE` skips creation of default tree from attributes, addition of schemas, addition of custom schemas and importing of LDIF files.

**Comment by fmulero** [comment]
Hi @johanneskastl. Thanks again for using the bitnami-openldap image and sharing your concerns. 

I have to recognize that this logic is not very clear. About your proposal, is likely nobody who is setting `LDAP_CUSTOM_SCHEMA_FILE` or `LDAP_CUSTOM_LDIF_DIR` would be setting any value for `LDAP_SKIP_DEFAULT_TREE ` at the moment. What would happen if a new version is released with your proposal? `ldap_create_tree ` will be executed trying to create the default tree if you don't say explicitly the opposite and it could crash if you are setting your own schema or tree.

I'd suggest something like this to just ignore `LDAP_SKIP_DEFAULT_TREE` if `LDAP_CUSTOM_LDIF_DIR` or `LDAP_CUSTOM_SCHEMA_FILE` are set:
```bash
ldap_initialize() {
    info "Initializing OpenLDAP..."

    ldap_configure_permissions
    if ! is_dir_empty "$LDAP_DATA_DIR"; then
        info "Using persisted data"
    else
        # Create OpenLDAP online configuration
        ldap_create_online_configuration
        ldap_start_bg
        ldap_admin_credentials
        if [ "$LDAP_ALLOW_ANON_BINDING" == 'no' ]; then
            ldap_disable_anon_binding
        fi
        if is_boolean_yes "$LDAP_ENABLE_TLS"; then
            ldap_configure_tls
        fi
        # Initialize OpenLDAP with schemas/tree structure
        ldap_add_schemas
        if [[ -f "$LDAP_CUSTOM_SCHEMA_FILE" ]]; then
            ldap_add_custom_schema
        fi
        if ! is_dir_empty "$LDAP_CUSTOM_LDIF_DIR"; then
            ldap_add_custom_ldifs
        else if is_boolean_yes "$LDAP_SKIP_DEFAULT_TREE";
            ldap_create_tree
        else
            info "Skipping default schemas/tree structure"
        fi
        ldap_stop
    fi
}
```
Add obviously amend the documentation.

Please create a PR to solve the issue. We will be happy to review it and provide feedback, and it will be easier for all to follow the discussions directly in the code. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines

**Comment by johanneskastl** [comment]
Dear Fran,

please see #87 for my original proposal and #88 for an approach following your proposal.

**Comment by fmulero** [comment]
Thanks Johannes,

#88 looks good to me. If everything is OK we will merge your changes soon and release a new version of the container. Good work 👍
