### ISSUE TITLE
Kubernetes CrashLoopBackOff without error in pod logs

### ISSUE THREAD

**Issue by johanneskastl** [bitnami/bitnami-docker-openldap#89]
### Name and Version

bitnami/openldap:2.5.11

### What steps will reproduce the bug?

I am running a single pod deployment of the bitnami docker-openldap image in a single-node Kubernetes cluster, using a persistent volume to make `/bitnami/openldap/data` persistent.

Unfortunately after the machine reboots for updates sometimes the pods goes into a **CrashLoopBackOff** error state without anything useful in the logs.

```
 16:06:44.21 INFO  ==> ** Starting LDAP setup **
 16:06:44.22 INFO  ==> Validating settings in LDAP_* env vars
 16:06:44.23 INFO  ==> Initializing OpenLDAP...
 16:06:44.23 DEBUG ==> Ensuring expected directories/files exist...
 16:06:44.24 INFO  ==> Using persisted data

 16:06:44.24 INFO  ==> ** LDAP setup finished! **
 16:06:44.26 INFO  ==> ** Starting slapd **
623f3a14.0ff360a1 0x7fa8ccacb000 @(#) $OpenLDAP: slapd 2.5.11 (Mar  1 2022 15:23:23) $
        @bc169e08a584:/bitnami/blacksmith-sandox/openldap-2.5.11/servers/slapd
623f3a14.100ccc3d 0x7fa8ccacb000 slapd stopped.
623f3a14.100d1fb9 0x7fa8ccacb000 connections_destroy: nothing to destroy.
```

### What is the expected behavior?

Ideally the pod should run flawlessly, just as it was when I created and configured it.

At least it should spit out some useful errors, what exactly is causing it to crash.

I already set `BITNAMI_DEBUG: 'true'` to get debug output, but to no avail.

### What do you see instead?

Kubernetes log from pod see above.

**Comment by rafariossaa** [comment]
Hi,
  I am not able to reproduce the issue, I tried killing the pod, and also in minikube and restarting it but I had no luck.
  Once this happen, how do you recover it ? is there any other useful information in the events ?

**Comment by johanneskastl** [comment]
Hi Rafael,

I was not able to reproduce this either by deleting the pod. But I might have just not waited long enough or tried often enough.

The only way to get it running again was deleting the deployment and the PVC, which means basically starting from scratch (empty LDAP tree, where LDIFs would then get imported or similar).

As I wrote, the pod's logs do not contain anything useful, neither does `describe`'ing the deployment, pod or replicaset.

Which events did you mean? Any other logs (inside the container?) that I should check?

**Comment by johanneskastl** [comment]
I did some more tests and even removed the files in `ldif_import` which is what LDAP_CUSTOM_LDIF_DIR is pointing to. But it makes no difference, the pod will not start and will immediately error out and end up in CrashLoopBackOff.

**Comment by rafariossaa** [comment]
I mean the k8s events, but it seems clear that the `slapd` daemon is stopping for some reason.
Maybe you could building you own image and changing the [log level](https://knowledgebase.progress.com/articles/Article/How-to-configure-OpenLDAP-logging-1307739574654) [here](https://github.com/bitnami/bitnami-docker-openldap/blob/fcf3b298a592a9f0b98edfd96e4aeef0662a9ac2/2.6/debian-10/rootfs/opt/bitnami/scripts/openldap/run.sh#L28). 
That way maybe we can have more info in what is happening.

**Comment by johanneskastl** [comment]
> I mean the k8s events, but it seems clear that the `slapd` daemon is stopping for some reason. Maybe you could building you own image and changing the [log level](https://knowledgebase.progress.com/articles/Article/How-to-configure-OpenLDAP-logging-1307739574654) [here](https://github.com/bitnami/bitnami-docker-openldap/blob/fcf3b298a592a9f0b98edfd96e4aeef0662a9ac2/2.6/debian-10/rootfs/opt/bitnami/scripts/openldap/run.sh#L28). That way maybe we can have more info in what is happening.

I just had a quick look, and the comment in line 27 makes me think it should be possible to add custom command line flags, without having to rebuild the image. I'll try to find out how to do that with Kubernetes.

Otherwise maybe I'll prepare a PR for increasing the loglevel if `BITNAMI_DEBUG` (or a new environment variable) is set to true.

**Comment by rafariossaa** [comment]
Let's wait until it gets reviewed and merged.

**Comment by johanneskastl** [comment]
I built an image using the code from my PR #91 and use that for setting the loglevel to 4.

I got more output, but it is not really helpful...

```
 09:08:28.10 INFO  ==> ** Starting LDAP setup **
 09:08:28.12 INFO  ==> Validating settings in LDAP_* env vars
 09:08:28.12 INFO  ==> Initializing OpenLDAP...
 09:08:28.13 DEBUG ==> Ensuring expected directories/files exist...
 09:08:28.13 INFO  ==> Using persisted data
 09:08:28.14 INFO  ==> ** LDAP setup finished! **

 09:08:28.15 INFO  ==> ** Starting slapd **
62456f8c.098619a0 0x7f8edebff000 @(#) $OpenLDAP: slapd 2.5.11 (Mar  1 2022 15:23:23) $
        @bc169e08a584:/bitnami/blacksmith-sandox/openldap-2.5.11/servers/slapd
62456f8c.0986fab4 0x7f8edebff000 daemon_init: ldap://:1389/ ldaps://:1636/ ldapi:///
62456f8c.09a0863c 0x7f8edebff000 send_ldap_result: err=32 matched="" text=""
62456f8c.09a14993 0x7f8edebff000 slapd stopped.
62456f8c.09a1b328 0x7f8edebff000 connections_destroy: nothing to destroy.
[deskmini-k3s|openldap-bitnami] kastl@laptop:/home/kastl/Kubernetes/Deskm
```

The only new thing is the daemon init line and `send_ldap_result: err=32 matched="" text=""`

**Comment by rafariossaa** [comment]
Hi,
  For the error, [it seems](https://ldapwiki.com/wiki/LDAP%20Result%20Codes) that maybe you entered a bad DN value for something that needed a correct DN value.
  Maybe, you are reusing the persisted data and the previous run where done with other parameters.

**Comment by johanneskastl** [comment]
> Hi, For the error, [it seems](https://ldapwiki.com/wiki/LDAP%20Result%20Codes) that maybe you entered a bad DN value for something that needed a correct DN value. Maybe, you are reusing the persisted data and the previous run where done with other parameters.

Thanks for the reply, @rafariossaa! 

Unfortunately I cannot test, as the cluster is having unrelated issues currently.

But: The pod was running fine when I last checked it before I noticed the CrashLoopBackOff. So either something got broken inside the persistent data during reboot/shutdown of the node, or the running configuration was slightly different from what was persisted.

I'll do some debugging and report back, once I find something. I'll close this for now and reopen if there is something that needs fixing.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your testing.
  Yes, please, don't hesitate to reopen this issue or to open a new one when you have more information.

**Comment by johanneskastl** [comment]
OK, using the freshly released image 2.5.11-debian-10-r73 and using `LDAP_LOGLEVEL: '1'` I got some more logs:

```
 14:30:56.27 INFO  ==> ** Starting slapd **
624b0120.10bf538f 0x7f4170109000 @(#) $OpenLDAP: slapd 2.5.11 (Mar  1 2022 15:23:23) $
        @bc169e08a584:/bitnami/blacksmith-sandox/openldap-2.5.11/servers/slapd
624b0120.10c0db3d 0x7f4170109000 daemon_init: listen on ldap://:1389/
624b0120.10c0e66e 0x7f4170109000 daemon_init: listen on ldaps://:1636/
624b0120.10c0e95e 0x7f4170109000 daemon_init: listen on ldapi:///
624b0120.10c0ec9d 0x7f4170109000 daemon_init: 3 listeners to open...
624b0120.10c0f15a 0x7f4170109000 ldap_url_parse_ext(ldap://:1389/)
624b0120.10c2bda2 0x7f4170109000 daemon: listener initialized ldap://:1389/
624b0120.10c2c757 0x7f4170109000 ldap_url_parse_ext(ldaps://:1636/)
624b0120.10c3285c 0x7f4170109000 daemon: listener initialized ldaps://:1636/
624b0120.10c33152 0x7f4170109000 ldap_url_parse_ext(ldapi:///)
624b0120.10c6978f 0x7f4170109000 daemon: listener initialized ldapi:///
624b0120.10c6a144 0x7f4170109000 daemon_init: 5 listeners opened
624b0120.10cc684f 0x7f4170109000 slapd init: initiated server.
624b0120.10cd318c 0x7f4170109000 slap_sasl_init: initialized!
624b0120.10d6134c 0x7f4170109000 mdb_back_initialize: initialize MDB backend
624b0120.10d61df1 0x7f4170109000 mdb_back_initialize: LMDB 0.9.29: (March 16, 2021)
624b0120.10d85377 0x7f4170109000 backend_startup_one: starting "cn=config"
624b0120.10d88cf5 0x7f4170109000 ldif_read_file: no entry file "/opt/bitnami/openldap/etc/slapd.d/cn=config.ldif"
624b0120.10d895e1 0x7f4170109000 send_ldap_result: conn=-1 op=0 p=0
624b0120.10d8b313 0x7f4170109000 slapd destroy: freeing system resources.
624b0120.10d936b1 0x7f4170109000 slapd stopped.
624b0120.10d98c20 0x7f4170109000 connections_destroy: nothing to destroy.
```

I started over and removed the PVC containing the "might be broken" configuration. I redeployed everything and checked. With the new image version (that contains some fixes in regards to what is being skipped at startup etc) I get the file that was missing somehow:
```
$ kex openldap-bitnami-757c684f48-t89zv -- bash
I have no name!@openldap-bitnami-757c684f48-t89zv:/$ ls -lh /opt/bitnami/openldap/etc/slapd.d/
total 4.0K
drwxr-x---. 1 1001 root 256 Apr  4 14:34 'cn=config'
-rw-------. 1 1001 root 670 Apr  4 14:34 'cn=config.ldif'
I have no name!@openldap-bitnami-757c684f48-t89zv:/$
```

So I will put this down to the configuration being created by an image with the faulty logic and hope, that this configuration now stays running. If not, I'll be back :-)

**Comment by johanneskastl** [comment]
And after another helm upgrade the CrashLoopBackOff error was back :-(

But I think I figured out what the problem was:
My helm chart only persisted `/bitnami/openldap/data/`, so the config in `/bitnami/openldap/slapd.d/` got lost and does not get recreated, as the startup script detects that there is already persisted data...

I now changed the chart to have the PVC mounted to `/bitnami/openldap/`, everything was created properly and after some pod deletions the pods come up fine.

So, hopefully it is solved **now** :-)

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for sharing your findings and sending a PR
