### ISSUE TITLE
Documentation 'Securing OpenLDAP traffic' wrong path

### ISSUE THREAD

**Issue by stefanpoeter** [bitnami/bitnami-docker-openldap#93]
### Name and Version

bitnami/openldap:2.5

### What steps will reproduce the bug?

 $ docker run --name openldap \
     -v /path/to/certs:/opt/bitnami/openldap/certs \
     -v /path/to/openldap-data-persistence:/bitnami/openldap/data \
     -e ALLOW_EMPTY_PASSWORD=yes \
     -e LDAP_ENABLE_TLS=yes \
     -e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt \
     -e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key \
     -e LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt \
     -e BITNAMI_DEBUG=true \
     bitnami/openldap:latest

### What is the expected behavior?

Everything should work out of the box.

### What do you see instead?

Permission issues when inspecting the logs

### Additional information

There is a wrong path on the Documentation:

    -v /path/to/openldap-data-persistence:/bitnami/openldap/data \

Should be

    -v /path/to/openldap-data-persistence:/OPT/bitnami/openldap/data \

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out.
  Would you like to send a PR to fix it ? We will be glad to review and merge it .
