### ISSUE TITLE
is_boolean_no: command not found

### ISSUE THREAD

**Issue by BlackRose01** [bitnami/bitnami-docker-openldap#95]
### Name and Version

bitnami/openldap:latest

### What steps will reproduce the bug?

Run `docker run -d --name openldap -e LDAP_ADMIN_USERNAME=admin -e LDAP_ADMIN_PASSWORD=admin -e LDAP_CONFIG_ADMIN_ENABLED=yes -e LDAP_CONFIG_ADMIN_PASSWORD=admin -p 1389:1389 -p 1636:1636 bitnami/openldap:latest `

### What do you see instead?

```log
 15:40:18.27 INFO  ==> ** Starting LDAP setup **
 15:40:18.52 INFO  ==> Validating settings in LDAP_* env vars
 15:40:18.66 INFO  ==> Initializing OpenLDAP...
 15:40:18.81 INFO  ==> Creating LDAP online configuration
 15:40:18.99 INFO  ==> Starting OpenLDAP server in background
 15:40:19.15 INFO  ==> Configure LDAP credentials for admin user
 15:40:19.28 INFO  ==> Adding LDAP extra schemas
/opt/bitnami/scripts/libopenldap.sh: line 477: is_boolean_no: command not found
 15:40:19.50 INFO  ==> Skipping default schemas/tree structure
 15:40:20.68 INFO  ==> ** LDAP setup finished! **
 15:40:20.92 INFO  ==> ** Starting slapd **
624c62e4.3abd0cb6 0x40023b2000 @(#) $OpenLDAP: slapd 2.6.1 (Mar  1 2022 15:23:28) $
	@57ed3f4ea4c3:/bitnami/blacksmith-sandox/openldap-2.6.1/servers/slapd
624c62e5.049189dd 0x40023b2000 slapd starting
```

### Additional information

Tried the image on an iMac nano with M1 processor and a Windows 10 Pro (Version: 21H2) laptop with an Intel Core i7-8550U. I also tried the images 2.5.11, 2.6 and 2.6.1

**Comment by cbandy** [comment]
Introduced in e8ec69e80da1e5088eaf74c692fbb981e4254fa5.

**Comment by BlackRose01** [comment]
Thank you for the information but the problem is already there. If you have a look on line 477 (file: [libopenldap.sh](https://github.com/bitnami/bitnami-docker-openldap/commit/e8ec69e80da1e5088eaf74c692fbb981e4254fa5#diff-64ff1fbf0b64ce272ac3cb1ba6fbaf18020deb4991b058855d9a4235c738edda)) in your mentioned commit then you will see that there will be used the wrong function call. The function does not exists in any lib* script.

**Comment by fmulero** [comment]
Thanks a lot. During today new images will be released with the fix. Sorry for the inconvenience

**Comment by cbandy** [comment]
2.5 also needs the fix.

https://github.com/bitnami/bitnami-docker-openldap/blob/c7bc3d85aef0506ac3d9c49cbcd86241f0bac4e4/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L477

https://github.com/bitnami/bitnami-docker-openldap/blob/c7bc3d85aef0506ac3d9c49cbcd86241f0bac4e4/2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L477

**Comment by fmulero** [comment]
All branches has been fixed, we are releasing it at the moment. During today all changes will be published
